// ui-mobile-vue/src/components/mobile/keyboard/keyboardComponent.vue
<template>
  <!-- PxyCommonUI 组件容器 -->
  <div ref="uiKeyboardRef" style=" position: 'absolute';zIndex: 2000; bottom: 0;width: '100%';"></div>
</template>

<script>
import { mapState, mapActions } from 'vuex';
import store from '@/store';
import PxyCommonUI from 'pxy_webcommonui';
const { Keyboard } = PxyCommonUI;

export default {
  name: "App",
  components: {},
  data() {
    return {
      keyboard: null,
    };
  },
  computed: {
    ...mapState({
      larksr: (state) => state.larksr,
    }),
    ...mapActions({
      // toggleVKeyboard: 'toggleVKeyboard',
    }),
  },
  mounted() {
    // Pxycommonui 组件 
    // @see https://github.com/pingxingyun/pxy_webcommonui
    this.keyboard = new Keyboard({
      // 必填项，挂载的根元素
      rootElement: this.$refs["uiKeyboardRef"], 
      larksr: this.larksr,
      language: this.larksr.params.language === 'en-US'? 'en':'zh'
    })
    this.keyboard.show();
    this.keyboard.on('keyboardVal', (e)=>{
      console.log('e',e.detail)
    })
    this.keyboard.on('toggleKeyboard', (e)=>{
      console.log('e',e.detail)
      store.dispatch('toggleVKeyboard');
    })
  },
  methods: {}
};
</script>

<style></style>

// ui-react/src/components/mobile/keyboard/keyboard.jsx

import PxyCommonUI from 'pxy_webcommonui';
import { useEffect, useRef } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { toggleVKeyboard } from '../../../store/modules/comm';


export default function Keyboard() {
  const dispatch = useDispatch();
  
  const larksr = useSelector(state => state.comm.larksr);
  const { Keyboard } = PxyCommonUI;

  const keyboard = useRef(null);
  const uiKeyboardRef = useRef(null);

  useEffect(() => {
    keyboard.current = new Keyboard({
      // 必填项，挂载的根元素
      rootElement: uiKeyboardRef.current, 
      larksr: larksr,
      language: larksr.params.language === 'en-US'? 'en':'zh'
    })
    keyboard.current.show();
    keyboard.current.on('keyboardVal', (e)=>{
      console.log('e',e.detail)
    })
    keyboard.current.on('toggleKeyboard', (e)=>{
      console.log('e',e.detail)
      dispatch(toggleVKeyboard());
    })
  }, []);
  return(
    <div ref={uiKeyboardRef} style={{'position': 'absolute','zIndex': 2000, 'bottom': 0,'width': '100%'}}></div>
  )
}
