// ui-react/src/components/mobile/vCursor/mouseButton/mouseButton.jsx
import { useState } from 'react';
import './mouseButton.scss';

export default function MouseButton(props) {

  const [isPressed, setIsPressed] = useState(false);
  const [dragStarted, setDragStarted] = useState(false);
  const [lastMovePositon, setLastMovePositon] = useState({
      x: 0,
      y: 0,
  });

  const onTouchStart = (e) => {
    // e.preventDefault();
    e.stopPropagation();
    props.touchstart(e);
    setIsPressed(true);
  };
  const onTouchMove = (e) => {
      // e.preventDefault();
      e.stopPropagation();
      // props.touchmove(e);
      const current = {
          x: e.targetTouches[0].clientX,
          y: e.targetTouches[0].clientY,
      } ;
      if (!dragStarted) {
        setDragStarted(true);
        setLastMovePositon(current);
        return;
      }
      const motion = {
          x: current.x - lastMovePositon.x, 
          y: current.y - lastMovePositon.y ,
      };
      props.drag(motion);
      setLastMovePositon(current);
  };
  const onTouchEnd = (e) => {
      // e.preventDefault();
      e.stopPropagation();
      props.touchend(e);
      setIsPressed(false);
      setDragStarted(false);
  }
  return(
    // onTouchCancle={onTouchEnd}
    <div className={`vmouse${props.classNameStr?props.classNameStr:''}`}
        style={props.style}
        onTouchStart={onTouchStart} 
        onTouchMove={onTouchMove} 
        onTouchEnd={onTouchEnd} >
        {props.content}
    </div>
  )
}

// ui-mobile-vue/src/components/mobile/v_cursor/mouse_button/mouse_button.vue
<template>
    <div class="vmouse" 
        v-on:touchstart="onTouchStart" 
        v-on:touchmove="onTouchMove" 
        v-on:touchend="onTouchEnd" 
        v-on:touchcancle="onTouchEnd"
    >
        <slot></slot>
    </div>
</template>
<script>
export default {
    props: [],
    data() {
        return {
            isPressed: false,
            dragStarted: false,
            lastMovePositon: {
                x: 0,
                y: 0,
            }
        }
    },
    methods: {
        onTouchStart(e) {
            e.preventDefault();
            e.stopPropagation();
            this.$emit('touchstart', e);
            this.isPressed = true;
        },
        onTouchMove(e) {
            e.preventDefault();
            e.stopPropagation();
            this.$emit('touchmove', e);
            const current = {
                x: event.targetTouches[0].clientX,
                y: event.targetTouches[0].clientY,
            } ;
            if (!this.dragStarted) {
                this.dragStarted = true;
                this.lastMovePositon = current;
                return;
            }
            const motion = {
                x: current.x - this.lastMovePositon.x, 
                y: current.y - this.lastMovePositon.y ,
            };
            // Log.info('motion', motion);
            this.$emit('drag', motion);
            this.lastMovePositon = current;
        },
        onTouchEnd(e) {
            e.preventDefault();
            e.stopPropagation();
            this.$emit('touchend', e);
            this.isPressed = false;
            this.dragStarted = false;
        }
    }
}
</script>
<style lang="scss" scoped>
@import "mouse_button.scss";
</style>
