// ui-mobile-vue/src/components/live_streaming/live_streaming.vue
<template>
    <div v-if="isLiveStream" :class="containerClass">
        <div class="icon" @click="togglePanel">
            <img src="@/assets/img/live.png" />
        </div>
        <div v-if="showSetup" class="setting" :style="viewPortStyle" @drag.stop @dragstart.stop @dragend.stop draggable="false">
            <div class="content" @drag.stop @dragstart.stop @dragend.stop draggable="false">
                <div class="closeBtn" @click="togglePanel">
                    <img src="@/assets/img/close.png" />
                </div>
                <p class="title">推流设置</p>
                <div class="item">
                    <label for="live-path">推流地址</label>
                    <input type="text" name="rtmp-path" id="rtmp-path" placeholder="推流地址" 
                         v-model="rtmpPath" @focus="onInputFocus" @blur="onInputBlur" @keyup.enter="onInputBlur"
                    />
                </div>
                <div class="item">
                    <label for="rtmp-key">密钥</label>
                    <input type="text" name="rtmp-key" id="rtmp-key" placeholder="密钥"
                        v-model="rtmpKey" @focus="onInputFocus" @blur="onInputBlur" @keyup.enter="onInputBlur"
                    />
                </div>
                <div class="item">
                    <label for="bitrate">码率</label>
                    <select v-model="selectCoderate" name="码率">
                        <option v-for="(coderate, key) in coderates" v-bind:value="coderate" v-bind:key="key">
                            {{ coderate }} kbps
                        </option>
                    </select>
                </div>
                <div class="item">
                    <label for="fps">帧率</label>
                    <select v-model="selectFps" name="帧率">
                        <option v-for="(fps, key) in fpss" v-bind:value="fps" v-bind:key="key">
                            {{ fps }} FPS
                        </option>
                    </select>
                </div>
                <div class="item">
                    <label for="res">分辨率</label>
                    <select v-model="selectRes" name="分辨率">
                        <option v-for="(res, key) in ress" v-bind:value="res" v-bind:key="key">
                            {{ res.width }} x {{ res.height }}
                        </option>
                    </select>
                </div>
                <div class="submit">
                    <button @click="onSubmit">确定</button>
                </div>
                <div class="status" :style="status.isError ? { color : 'red'} : {}">
                    <p>{{status.text}}</p>
                </div>
            </div>
        </div>
    </div>
</template>
<script>
import {
    mapState,
    mapGetters,
    mapActions,
}                                   from 'vuex';
import Log                          from "@/utils/log";
import Capabilities                 from '@/utils/capabilities';
import { LarkSR, LarkSRClientEvent, LoadAppliParamsFromUrl } from "larksr_websdk";

export default {
    components: {
    },
    data() {
        return {
            rtmpPath: '',
            rtmpKey: '',
            showSetup: false,
            selectCoderate: 2500,
            coderates: [
                2500,
                5000,
                8000,
                10000,
            ],
            selectFps: 30,
            fpss: [
                30,
                60,
            ],
            selectRes: {
                    width: 1280,
                    height: 720,
            },
            ress: [
                {
                    width: 1280,
                    height: 720,
                },
                {
                    width: 1920,
                    height: 1080
                }
            ],
            status: {
                isError: false,
                text: '',
            },
            mobileScreenLandscapState: false,
        }
    },
    computed: {
        containerClass() {
            if (this.audioInput && this.videoInput) {
                return this.isMobile ? 'live live-mobile live-slot-3' : 'live live-slot-3';
            } else if (this.audioInput || this.videoInput) {
                return this.isMobile ? 'live live-mobile live-slot-2' : 'live live-slot-2';
            } else {
                return this.isMobile ? 'live live-mobile' : 'live';
            }
        },
        isLiveStream() {
            // return true;
            return this.larksr?.params.liveStreaming;
        },
        audioInput() {
            // return true;
            return this.larksr?.params.audioInput;
        },
        videoInput() {
            // return true;
            return this.larksr?.params.videoInput;
        },
        ...mapState({
            larksr: state => state.larksr,  
            ui: state => state.ui,
            isMobile: state => state.isMobile,
            viewPort: state => state.viewPort,
        }),
        ...mapGetters([
            'viewPortStyle',
            "screenOrientation",
        ]),
    },
    methods: {
        onSubmit() {
            Log.info('on submit live streaming', this.rtmpKey, this.rtmpPath, this.selectFps, this.selectRes, this.selectCoderate);
            if (!this.rtmpPath) {
                this.status = {
                    isError: true,
                    text: '必须填写推流地址',
                }
                return;
            }

            this.larksr.StartCloudLiveStreaming({
                path: this.rtmpPath,
                key: this.rtmpKey,
                width: this.selectRes.width, 
                height: this.selectRes.height,
                framerate: this.selectFps,
                bitrate: this.selectCoderate
            })
            .then((res) => {
                this.status = {
                    isError: false,
                    text: '准备推流中...',
                }
            })
            .catch((err) => {
                this.status = {
                    isError: true,
                    text: err,
                }
            });
        },
        onInputFocus() {
            if (this.isMobile && this.screenOrientation == "landscape") {
                this.larksr?.screenState.setMobileForceLandScape(false);
                this.mobileScreenLandscapState = true;
            }
            this.larksr?.op.setKeyboardEnable(false);
        },
        onInputBlur() {
            if (this.mobileScreenLandscapState) {
                this.larksr?.screenState.setMobileForceLandScape(true);
                this.mobileScreenLandscapState = false;
            }
            this.larksr?.op.setKeyboardEnable(true);
        },
        togglePanel() {
            Log.info("toggel live panel");
            this.showSetup = !this.showSetup;
        },
        onRtmpStreamState(e) {
            Log.info("onRtmpStreamState", e);
            this.toast(e.data.desc);
            this.status = {
                isError: false,
                text: e.data.desc,
            }
        },
        onRtmpStreamError(e) {
            Log.info("onRtmpStreamError", e);
            this.showSetup = true;
            this.status = {
                isError: true,
                text: e.data.desc,
            }
        },
        ...mapActions({
            toast: "toast/toast",
            notify: "notifyBar/notify",
            alert: "modalAlert/showModalAlert",
        }),
    },
    mounted() {
        Log.info('live larksr', this.larksr);
        this.larksr.on(LarkSRClientEvent.RTMP_STREAM_STATE, this.onRtmpStreamState, this);
        this.larksr.on(LarkSRClientEvent.RTMP_STREAM_ERROR, this.onRtmpStreamError, this);
    },
    unmounted() {
        Log.info("relase livestreaming icon");
    },
}
</script>
<style lang="scss" scoped>
@import "live_streaming.scss";
</style>

// ui-react/src/components/liveStreaming/liveStreaming.jsx
import './liveStreaming.scss';
import Log from "@/utils/log";
import { LarkSRClientEvent } from "larksr_websdk";
import ContentAlert from '../customContentAlert/customContentAlert';
import { setIsShowStreamAlert, setRtmpstreamstate, setRtmpstreamForm  } from '../../store/modules/modalStream';
import { setCustomContentAlertTitle } from '../../store/modules/customContentAlert';
import { toastAct } from '../../store/modules/toast';
import { useDispatch, useSelector } from 'react-redux';
import { CloseOutlined } from '@ant-design/icons'
import { useEffect, useState } from 'react';
import { Input, Select } from 'antd';
import Btn from '../button/button';

export default function LiveStreaming() {
  const dispatch = useDispatch();

  const larksr = useSelector(state => state.comm.larksr);
  const ui = useSelector(state => state.comm.ui);
  const isMobile = useSelector(state => state.comm.isMobile);


  const [rtmpPath, setRtmpPath] = useState('');
  const [rtmpKey, setRtmpKey] = useState('');
  // showSetup: false,
  const [selectCoderate, setSelectCoderate] = useState(2500);
  const [selectFps, setSelectFps] = useState(30);
  const [selectRes, setSelectRes] = useState({
    width: 1280,
    height: 720,
  });
  const [status, setStatus] = useState({
      isError: false,
      text: '',
      code: ''
  })
  const [mobileScreenLandscapState, setMobileScreenLandscapState] = useState(false);

  // const [audioInput, setAudioInput] = useState(false);
  // const [videoInput, setVideoInput] = useState(false);
  // const [containerClass, setContainerClass] = useState('');
  const [screenOrientation, setScreenOrientation] = useState('portrait');
  useEffect(() => {
    setAudioInput(larksr?.params.audioInput);
    setVideoInput(larksr?.params.videoInput);
    const screenOrientation = larksr ? larksr.screenState.screenOrientation : 'portrait';
    setScreenOrientation(screenOrientation);
  }, [larksr]);

  // useEffect(() => {
  //   if (audioInput && videoInput) {
  //     return isMobile ? setContainerClass('live live-mobile live-slot-3') : setContainerClass('live live-slot-3');
  //   } else if (audioInput || videoInput) {
  //       return isMobile ? setContainerClass('live live-mobile live-slot-2') : setContainerClass('live live-slot-2');
  //   } else {
  //       return isMobile ? setContainerClass('live live-mobile') : setContainerClass('live');
  //   }
  // }, [isMobile])


  const onCancel = () => {
    dispatch(setIsShowStreamAlert(false));
    dispatch(setCustomContentAlertTitle(''));
  };
  const onSubmit = () => {
      Log.info('on submit live streaming', rtmpKey, rtmpPath, selectFps, {...selectRes}, selectCoderate);
      if (!rtmpPath) {
        setStatus({
          isError: true,
          text: ui.liveStreamTip,
          code: ''
        })
        return;
      }

      larksr.StartCloudLiveStreaming({
          path: rtmpPath,
          key: rtmpKey,
          width: selectRes.width,
          height: selectRes.height,
          framerate: selectFps,
          bitrate: selectCoderate
      })
      .then((res) => {
        setStatus({
          isError: false,
          text: ui.liveStreamPrepare,
          code: res.state || ''
        })
        dispatch(setRtmpstreamForm({
          rtmpPath: rtmpPath,
          rtmpKey: rtmpKey,
          codeRate: selectCoderate,
          frameRate: selectFps,
          resolution: {...selectRes}
        }));
      })
      .catch((err) => {
        setStatus({
          isError: true,
          text: err,
          code: ''
        })
        dispatch(setRtmpstreamForm(null));
      });
  };
  const onCancelLive = () => {
      Log.info('on close live streaming');
      larksr.StopLiveStreaming();
      dispatch(setRtmpstreamstate(null));
      dispatch(setRtmpstreamForm(null));
  };
  const onInputFocus = () => {
      if (isMobile && screenOrientation == "landscape") {
          larksr?.screenState.setMobileForceLandScape(false);
          setMobileScreenLandscapState(true);
      }
      larksr?.op.setKeyboardEnable(false);
  };
  const onInputBlur = () => {
      if (mobileScreenLandscapState) {
          larksr?.screenState.setMobileForceLandScape(true);
          setMobileScreenLandscapState(false);
      }
      larksr?.op.setKeyboardEnable(true);
  };
  const onRtmpStreamState = (e) => {
      Log.info("onRtmpStreamState", e);
      dispatch(toastAct(e.data.desc));
      setStatus({
        isError: true,
        text: e.data.desc,
        code: e.data.state || ''
      })
      
      dispatch(setRtmpstreamstate(status));
  };
  const onRtmpStreamError = (e) => {
      Log.info("onRtmpStreamError", e);
      setStatus({
        isError: true,
        text: e.data.desc,
        code: ''
      })
      
      dispatch(setRtmpstreamstate(status));
  };

  const rtmpstreamstate = useSelector(state => state.modalStream.rtmpstreamstate);
  const rtmpstreamForm = useSelector(state => state.modalStream.rtmpstreamForm);
  useEffect(() => {
    Log.info('live larksr', larksr);
    larksr.on(LarkSRClientEvent.RTMP_STREAM_STATE, onRtmpStreamState);
    larksr.on(LarkSRClientEvent.RTMP_STREAM_ERROR, onRtmpStreamError);

    if (rtmpstreamstate!==null) {
        status.isError = rtmpstreamstate.isError||'';
        status.text = rtmpstreamstate.text||'';
        status.code = rtmpstreamstate.code||'';
    }
    if (rtmpstreamForm!==null) {
        setRtmpKey(rtmpstreamForm.rtmpKey);
        setRtmpPath(rtmpstreamForm.rtmpPath);
        setSelectCoderate(rtmpstreamForm.codeRate);
        setSelectFps(rtmpstreamForm.frameRate);
        setSelectRes({
          width: rtmpstreamForm.resolution.width,
          height: rtmpstreamForm.resolution.height
        });
    }

    return () => {
      Log.info("relase livestreaming icon");
    }
  }, [])
  return(
    <ContentAlert
      customContentStyle={{'width': larksr?.screenState.viewPort.width, 'height': larksr?.screenState.viewPort.height}}
      close={
        <div onClick={onCancel}>
          <CloseOutlined/>
        </div>
      }
      content={
        <div className="stream" >
          {/* @drag.stop @dragstart.stop @dragend.stop */}
          <div className="content" draggable={false}>
              <div className="stream-input">
                  <span>{ ui.liveUrl }</span>
                  <Input value={rtmpPath} placeholder={ui.liveUrl} onChange={e => setRtmpPath(e)} onFocus={onInputFocus} onBlur={onInputBlur}  onPressEnter={onInputBlur} />
              </div>
              <div className="stream-input">
                  <span>{ ui.liveKey }</span>
                  <Input value={rtmpKey} placeholder={ui.liveKey} onChange={e => setRtmpKey(e)} onFocus={onInputFocus} onBlur={onInputBlur}  onPressEnter={onInputBlur} />
              </div>
              <div className="stream-input">
                <span>{ ui.liveBitrate }</span>
                <Select 
                    value={selectCoderate}
                    placeholder={ui.liveBitrate}
                    onChange={e => setSelectCoderate(e)}
                    options={[
                      {value: 2500, label: 2500+' kbps'},
                      {value: 5000, label: 5000+' kbps'},
                      {value: 8000, label: 8000+' kbps'},
                      {value: 10000, label: 10000+' kbps'},
                    ]}
                  />
              </div>
              <div className="stream-input">
                <span>{ ui.liveFPS }</span>
                <Select 
                    value={selectFps}
                    onChange={e => setSelectFps(e)}
                    placeholder={ui.liveFPS}
                    options={[
                      {value: 30, label: 30+' FPS'},
                      {value: 60, label: 60+' FPS'},
                    ]}
                  />
              </div>
              <div className="stream-input">
                  <span>{ ui.liveRes }</span>
                  <Select 
                      value={selectRes}
                      placeholder={ui.liveRes}
                      onChange={e => { const val=e.split('-'); setSelectRes({width: val[0], height: val[1]})}}
                      options={[
                        {value: '1280-720', label: <span>1280 x 720</span>},
                        {value: '1920-1080', label: <span>1920 x 1080</span>},
                        {value: '720-1280', label: <span>720 x 1280</span>},
                        {value: '1080-1920', label: <span>1080 x 1920</span>},
                      ]}
                    />
              </div>
              <div className="customContentAlert-divider"></div>
              <div className="status" style={status.isError ? { color : '#F56C6C'} : {}}>
                  <p>{status.text}</p>
              </div>
              <div className="button-group">
                { status.code == 1 && <Btn className="submit" title={ui.close} submit={false} click={onCancelLive}/>}
                { status.code !== 1 && <Btn className="submit" title={ui.liveSubmit} submit={false} click={onSubmit}/>}
                  
              </div>
          </div>
      </div>
      }
    >
    </ContentAlert>
  )
}
