// ui-react/src/components/customContentAlert/customContentAlert.jsx
import { useDispatch, useSelector } from 'react-redux'
import './customContentAlert.scss'
import { useEffect, useState } from 'react';

export default function customContentAlert({close, content, alertPositionStyle, customContentStyle}) {
  const dispatch = useDispatch();
  
  const larksr = useSelector(state => state.comm.larksr);
  const customContentAlertTitle = useSelector(state => state.customContentAlert.customContentAlertTitle);
  const viewPort = larksr ? larksr.screenState.viewPort : { width: 1920, height: 1080 };

  const [viewPortStyles, setViewPortStyles] = useState({});
  useEffect(() => {
    if( customContentStyle) {
      setViewPortStyles(customContentStyle);
    } else {
      setViewPortStyles({
        'width': viewPort.width+'px'
      })
    }
  }, [customContentStyle, viewPort])
  return (
    <div className="customAlert" style={viewPortStyles}>        
        <div className="customAlert-container" style={alertPositionStyle}>
            <div className="customAlert-title">
                <div>
                    <p>{customContentAlertTitle}</p>
                </div>
                {close}
            </div>
            <div className="customAlert-content">
              {content}
            </div>
        </div>
    </div>
  )
}

// ui-mobile-vue-new/src/components/custom_content_alert/custom_content_alert.vue
<template>
    <div class="customContentAlert" :style="viewPortStyles">        
        <div class="customContentAlert-container" :style="alertPositionStyle">
            <div class="customContentAlert-title">
                <div>
                    <p>{{customContentAlertTitle}}</p>
                </div>
                <slot name="close"></slot>
            </div>
            <div class="customContentAlert-content">
                <slot name="content"></slot>
            </div>
        </div>
    </div>
</template>
<script>
import { mapState, mapGetters } from 'vuex'

export default {
    name: 'CustomContentAlert',
    props: {
        alertPositionStyle: {
            type: Object,
            require: false
        },
        customContentStyle: {
            type: String,
            require: false
        }
    },
    computed: {
        ...mapState({
            customContentAlertTitle: state => state.customContentAlert.customContentAlertTitle
        }),
        viewPortStyles() {
            if(this.customContentStyle) {
                return this.customContentStyle;
            } else {
                return {
                    'width': this.viewPort.width+'px'
                }
            }
        },
        ...mapGetters([
            'viewPortStyle',
            'viewPort'
        ]),
    },
    methods: {},
    mounted() {},
    beforeDestroy() {},
}
</script>
<style lang="scss" scoped>
@import "custom_content_alert.scss";
</style>
