// ui-react/src/components/aerialView/aerialView.jsx
import './aerialView.scss';
import Log from "@/utils/log";
import ContentAlert from '../customContentAlert/customContentAlert';
import { setCustomContentAlertTitle } from '../../store/modules/customContentAlert';
import { setAerialViewCheck, setAeriaViewBoxEnd } from '../../store/modules/modalSetting';
import { setShowAerialView, toggleAerailView } from '../../store/modules/comm';
import { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { CloseOutlined } from '@ant-design/icons';
import Btn from '../button/button';

export default function AerialView() {
  const dispatch = useDispatch();

  const isMobile = useSelector(state => state.comm.isMobile);
  const ui = useSelector(state => state.comm.ui);
  const larksr = useSelector(state => state.comm.larksr);
  const aeriaViewBoxEnd = useSelector(state => state.modalSetting.aeriaViewBoxEnd);

  const [alertPositionStyle, setAlertPositionStyle] = useState({});
  const [containerSize, setContainerSize] = useState({width: 0, height: 0});
  const [boxSize, setBoxSize] = useState({width: 0, height: 0});
  const [start, setStart] = useState(false);
  const [boxPosition, setBoxPosition] = useState({x: 0, y: 0});
  const [offsetPositon, setOffsetPositon] = useState({x: 0, y: 0});
  const [backgroundImage, setBackgroundImage] = useState("");

  useEffect(() => {
    if(isMobile) {
      setAlertPositionStyle({
          top: '75px',
          left: '20px',
          position: 'absolute'
      });
  } else {
    setAlertPositionStyle({
          top: '75px',
          right: '20px',
          position: 'absolute'
      });
  }
  }, [isMobile]);

  
  const [containerStyle, setContainerStyle] = useState({});
  useEffect(() => {
    let res = {};
    if (containerSize.width && containerSize.height) {
      res.width = containerSize.width + "px";
      res.height = containerSize.height + "px";
    } 
    if (backgroundImage) {
      res.backgroundImage = `url( ${backgroundImage})`;
    }
    setContainerStyle(preData => res);
  }, [backgroundImage, containerSize]);

  const onCancel = () => {
    dispatch(setCustomContentAlertTitle(''));
    dispatch(setAerialViewCheck(false));
    onClose();
  };

  const aerialViewContainerRef = useRef(null);
  const aerialViewBoxRef = useRef(null);
  const onStart = (e) => {
      // e.preventDefault();
      e.stopPropagation();

      let clientX = 0;
      let clientY = 0;

      let screenOrientation = larksr?.screenState.screenOrientation;

      let isLandscape = screenOrientation === 'landscape';

      if (e.changedTouches) {
          clientX = e.changedTouches[0].clientX;
          clientY = e.changedTouches[0].clientY;
      } else {
          clientX = e.clientX;
          clientY = e.clientY;
      }

      let containerSize = aerialViewContainerRef.current.getBoundingClientRect();
      let viewboxSize = aerialViewBoxRef.current.getBoundingClientRect();

      if (isLandscape) {
          const containerWidth = containerSize.width;
          containerSize.width = containerSize.height;
          containerSize.height = containerWidth;

          const viewboxWidth = viewboxSize.width;
          viewboxSize.width = viewboxSize.height;
          viewboxSize.height = viewboxWidth;
      }

      let px = clientX - viewboxSize.left;
      let py = clientY - viewboxSize.top;

      if (isLandscape) {
          px = clientY - viewboxSize.top;
          py = viewboxSize.height - (clientX - viewboxSize.left);

          // Log.info("start isLandscape X", px, viewboxSize, containerSize);
          // Log.info("start isLandscape Y", py, clientX, viewboxSize, containerSize);
      }

      setOffsetPositon({
        x: px,
        y: py
      });
      setStart(true);
      Log.info("aerial box drag start", viewboxSize, offsetPositon);
  };
  const onMove = (e) => {
      if (!start) {
          return;
      }

      // e.preventDefault();
      e.stopPropagation();

      let screenOrientation = larksr?.screenState.screenOrientation;

      let isLandscape = screenOrientation === 'landscape';

      let clientX = 0;
      let clientY = 0;

      if (e.changedTouches) {
          clientX = e.changedTouches[0].clientX;
          clientY = e.changedTouches[0].clientY;
      } else {
          clientX = e.clientX;
          clientY = e.clientY;
      }

      let containerSize = aerialViewContainerRef.current.getBoundingClientRect();
      let viewboxSize = aerialViewBoxRef.current.getBoundingClientRect();

      if (isLandscape) {
          const containerWidth = containerSize.width;
          containerSize.width = containerSize.height;
          containerSize.height = containerWidth;

          const viewboxWidth = viewboxSize.width;
          viewboxSize.width = viewboxSize.height;
          viewboxSize.height = viewboxWidth;
      }

      let offsetX = clientX - viewboxSize.left;
      let offsetY = clientY - viewboxSize.top;

      let px = clientX - offsetPositon.x - containerSize.x;
      let py = clientY - offsetPositon.y - containerSize.y;

      if (isLandscape) {
          px = clientY - offsetPositon.x - containerSize.y;
          py = viewboxSize.height - (clientX - containerSize.x) + offsetPositon.y;

      }

      if (px < 0) {
          px = 0;
      }

      if (py < 0) {
          py = 0;
      }

      if (px > containerSize.width - viewboxSize.width) {
          px = containerSize.width - viewboxSize.width;
      }

      if (py > containerSize.height - viewboxSize.height) {
          py = containerSize.height - viewboxSize.height;
      }
      setBoxPosition({
        x: px,
        y: py
      });
      
  };
  const onEnd = (e) => {
      // if(e)e.preventDefault();
      if(e)e.stopPropagation();

      let screenOrientation = larksr?.screenState.screenOrientation;

      let isLandscape = screenOrientation === 'landscape';
      
      let containerSize = aerialViewContainerRef.current.getBoundingClientRect();
      let viewboxSize = setBoxSizeFn(containerSize);

      if (isLandscape) {
          const containerWidth = containerSize.width;
          containerSize.width = containerSize.height;
          containerSize.height = containerWidth;

          const viewboxWidth = viewboxSize.width;
          viewboxSize.width = viewboxSize.height;
          viewboxSize.height = viewboxWidth;
      }

      let px = boxPosition.x;
      let py = boxPosition.y;

      let scale = larksr?.currentAppSize ? larksr.currentAppSize.width / containerSize.width : 1;

      let box = {
          x: px * scale,
          y: py * scale,
          width: viewboxSize.width * scale,
          height: viewboxSize.height * scale,
      };

      Log.info("update box " ,viewboxSize, scale, box);

      if (larksr.updateAerialview) {
          larksr.updateAerialview(box);
          dispatch(setAeriaViewBoxEnd(box));
      }
      setStart(false);
  };
  const onHide = () => {
      dispatch(setShowAerialView(false));
  };
  const onClose = () => {
      larksr.stopAerialview();
      dispatch(toggleAerailView());
      dispatch(setAeriaViewBoxEnd(null));
  };
  const init = () => {
      let screenOrientation = larksr?.screenState.screenOrientation;

      let isLandscape = screenOrientation === 'landscape';

      let containerSize = aerialViewContainerRef.current.getBoundingClientRect();
      // console.log('初始化传值',aerialViewContainerRef.current.getBoundingClientRect().height,containerSize)
      let viewboxSize = setBoxSizeFn(containerSize);

      if (isLandscape) {
          const containerWidth = containerSize.width;
          containerSize.width = containerSize.height;
          containerSize.height = containerWidth;

          const viewboxWidth = viewboxSize.width;
          viewboxSize.width = viewboxSize.height;
          viewboxSize.height = viewboxWidth;
      }

      if (!larksr) {
          Log.warn("larksr not inited");
          return;
      }

      let scale = larksr.currentAppSize.width / containerSize.width;

      let asp = larksr.currentAppSize.height / larksr.currentAppSize.width;

      containerSize.height = asp * containerSize.width;
      viewboxSize.height = asp * viewboxSize.width;


      Log.info('aerial view mounted', larksr.currentAppSize, asp, containerSize, viewboxSize);

      if (larksr.startAerialview) {
          // 恢复隐藏选择框之前的坐标位置
          if(aeriaViewBoxEnd) {
            setBoxPosition({
              x: aeriaViewBoxEnd.x/scale,
              y: aeriaViewBoxEnd.y/scale
            });
            larksr.startAerialview(aeriaViewBoxEnd, 1000, containerSize.width, containerSize.height);
          } else {
              larksr.startAerialview({
                  x: 0,
                  y: 0,
                  width: viewboxSize.width * scale,
                  height: viewboxSize.height * scale,
              }, 1000, containerSize.width, containerSize.height);
              setBoxPosition({
                x: 0,
                y: 0
              });
          }            
      }
      setContainerSize({
        width: containerSize.width,
        height: containerSize.height
      });

      // larksr.on("aerialviewscreen", (e) => {
      //     // Log.info("on aerialviewscreen", e, {"background-image": "url(" + e.data + ")" });
      //     setBackgroundImage(e.data);
      // })
  };

  const aeriaViewSelectScale = useSelector(state => state.modalSetting.aeriaViewSelectScale);
  const setBoxSizeFn = (containerSize) => {
      let val = {}
      if(aeriaViewSelectScale==='21') {
        val = {
          width: containerSize.width/2,
          height: containerSize.height/2
        }
      } else if(aeriaViewSelectScale==='31') {
        val = {
          width: containerSize.width/3,
          height: containerSize.height/3
        };
      } else if(aeriaViewSelectScale==='41') {
        val = {
          width: containerSize.width/4,
          height: containerSize.height/4
        }
      } 
      setBoxSize(val);  
      return val;
  };

  const [boxStyle, setBoxStyle] = useState({
    width: 'px2rem(250)',
    height: 'px2rem(250)'
  });
  useEffect(() => {
    let size = {};
    if(boxSize.width && boxSize.height) {
      size.width = boxSize.width + "px";
      size.height = boxSize.height + "px"
    };

    setBoxStyle({
      top: boxPosition.y + "px",
      left: boxPosition.x + "px",
      ...size
    })
  }, [boxPosition, boxSize, backgroundImage]);

  // 是否执行过初始化方法
  const [initFlag, setInitFlag] = useState(false);
  useEffect(() => {
    larksr.on("aerialviewscreen", (e) => {
      if(!initFlag) setInitFlag(true);
      // Log.info("on aerialviewscreen", e, {"background-image": "url(" + e.data + ")" });
      setBackgroundImage(preData => e.data);
    })
  }, [aeriaViewSelectScale, larksr]);
  useEffect(() => {
    dispatch(setAeriaViewBoxEnd(null));
    init(); 
    onEnd();    
  }, [initFlag])
  const showAerialView = useSelector(state => state.comm.showAerialView);
  return(
    <ContentAlert 
      alertPositionStyle={alertPositionStyle}
      close={
        <div onClick={onCancel}>
          <CloseOutlined style={{fontSize: '1.8rem'}} />
        </div>
      }
      content={
        <div>
          <div ref={aerialViewContainerRef} className="aerial-view-container" style={containerStyle}>
                <div ref={aerialViewBoxRef} className="aerial-view-box" style={boxStyle}
                    onMouseDown={onStart}
                    onMouseUp={onEnd}
                    onMouseLeave={onEnd}
                    onMouseMove={onMove}
                    onTouchStart={onStart}
                    onTouchMove={onMove}
                    onTouchEnd={onEnd}
                >
                </div>
            </div>
            <div className="customContentAlert-divider"></div>
            <div className="button-group" >
              <p>{JSON.stringify(showAerialView)}</p>
              <Btn className="submit" title={ui.hideAerial} submit={false} click={onHide} />
            </div>
        </div>
      }
    >
    </ContentAlert>
  )
}

// ui-mobile-vue/src/components/aerial_view/aerial_view.vue
<template>
<div ref="aerial-view-container" class="aerial-view-container" :style="containerStyle">
    <div class="btn btn-hide" v-on:click="onHide">{{ ui.hideAerial }}</div>
    <div class="btn btn-close" v-on:click="onClose">{{ ui.closeAerial }}</div>
    <div ref="aerial-view-box" class="aerial-view-box" :style="boxStyle"
        v-on:mousedown="onStart"
        v-on:mouseup="onEnd"
        v-on:mousecancel="onEnd"
        v-on:mouseleave="onEnd"
        v-on:mousemove="onMove"
        v-on:touchstart="onStart"
        v-on:touchmove="onMove"
        v-on:touchcancle="onEnd"
        v-on:touchend="onEnd"
    >
    </div>
</div>
</template>
<script>
import {
    mapState,
    mapGetters,
    mapActions,
}                                   from 'vuex';
import Log                          from "@/utils/log";
import Capabilities                 from '@/utils/capabilities';

export default {
    components: {
    },
    data() {
        return {
            containerSize: {width: 0, height: 0},
            boxSize: {width: 0, height: 0},
            start: false,
            boxPosition: {x: 0, y: 0},
            offsetPositon: {x: 0, y: 0},
            backgroundImage: "",
        }
    },
    computed: {
        containerStyle() {
            let res = "";
            if (this.containerSize.width && this.containerSize.height) {
                res += "width: " + this.containerSize.width + "px;height:" + this.containerSize.height + "px;";
            } 
            if (this.backgroundImage) {
                res += "background-image: url(" + this.backgroundImage + ");";
            }
            // Log.info("containerStyle ", res);
            return res;
        },
        boxStyle() {
            let size = this.boxSize.width && this.boxSize.height ? "width:" + this.boxSize.width + "px;height:" + this.boxSize.height + "px;" : "";
            return "top:" + this.boxPosition.y + "px;left:" + this.boxPosition.x + "px;" + size;
        },
        ...mapState({
            larksr: state => state.larksr,  
            ui: state => state.ui,
            isMobile: state => state.isMobile,
            showAerialView: state => state.showAerialView,
        }),
    },
    methods: {
        onStart(e) {
            e.preventDefault();
            e.stopPropagation();

            let clientX = 0;
            let clientY = 0;

            let screenOrientation = this.larksr?.screenState.screenOrientation;

            let isLandscape = screenOrientation === 'landscape';

            if (e.changedTouches) {
                clientX = e.changedTouches[0].clientX;
                clientY = e.changedTouches[0].clientY;
            } else {
                clientX = e.clientX;
                clientY = e.clientY;
            }

            let containerSize = this.$refs["aerial-view-container"].getBoundingClientRect();
            let viewboxSize = this.$refs["aerial-view-box"].getBoundingClientRect();

            if (isLandscape) {
                const containerWidth = containerSize.width;
                containerSize.width = containerSize.height;
                containerSize.height = containerWidth;

                const viewboxWidth = viewboxSize.width;
                viewboxSize.width = viewboxSize.height;
                viewboxSize.height = viewboxWidth;
            }

            let px = clientX - viewboxSize.left;
            let py = clientY - viewboxSize.top;

            if (isLandscape) {
                px = clientY - viewboxSize.top;
                py = viewboxSize.height - (clientX - viewboxSize.left);

                // Log.info("start isLandscape X", px, viewboxSize, containerSize);
                // Log.info("start isLandscape Y", py, clientX, viewboxSize, containerSize);
            }

            this.offsetPositon.x = px;
            this.offsetPositon.y = py;

            this.start = true;
            Log.info("aerial box drag start", viewboxSize, this.offsetPositon);
        },
        onMove(e) {
            if (!this.start) {
                return;
            }

            e.preventDefault();
            e.stopPropagation();

            let screenOrientation = this.larksr?.screenState.screenOrientation;

            let isLandscape = screenOrientation === 'landscape';

            let clientX = 0;
            let clientY = 0;

            if (e.changedTouches) {
                clientX = e.changedTouches[0].clientX;
                clientY = e.changedTouches[0].clientY;
            } else {
                clientX = e.clientX;
                clientY = e.clientY;
            }

            let containerSize = this.$refs["aerial-view-container"].getBoundingClientRect();
            let viewboxSize = this.$refs["aerial-view-box"].getBoundingClientRect();

            if (isLandscape) {
                const containerWidth = containerSize.width;
                containerSize.width = containerSize.height;
                containerSize.height = containerWidth;

                const viewboxWidth = viewboxSize.width;
                viewboxSize.width = viewboxSize.height;
                viewboxSize.height = viewboxWidth;
            }

            let offsetX = clientX - viewboxSize.left;
            let offsetY = clientY - viewboxSize.top;

            let px = clientX - this.offsetPositon.x - containerSize.x;
            let py = clientY - this.offsetPositon.y - containerSize.y;

            if (isLandscape) {
                px = clientY - this.offsetPositon.x - containerSize.y;
                py = viewboxSize.height - (clientX - containerSize.x) + this.offsetPositon.y;

                // Log.info("isLandscape X", px, clientY, this.offsetPositon, containerSize);
                // Log.info("isLandscape Y", py, clientX, this.offsetPositon, containerSize);
            }

            if (px < 0) {
                px = 0;
            }

            if (py < 0) {
                py = 0;
            }

            if (px > containerSize.width - viewboxSize.width) {
                px = containerSize.width - viewboxSize.width;
            }

            if (py > containerSize.height - viewboxSize.height) {
                py = containerSize.height - viewboxSize.height;
            }
            this.boxPosition = {
                x: px,
                y: py,
            }
        },
        onEnd(e) {
            e.preventDefault();
            e.stopPropagation();

            let screenOrientation = this.larksr?.screenState.screenOrientation;

            let isLandscape = screenOrientation === 'landscape';
            
            let containerSize = this.$refs["aerial-view-container"].getBoundingClientRect();
            let viewboxSize = this.$refs["aerial-view-box"].getBoundingClientRect();

            if (isLandscape) {
                const containerWidth = containerSize.width;
                containerSize.width = containerSize.height;
                containerSize.height = containerWidth;

                const viewboxWidth = viewboxSize.width;
                viewboxSize.width = viewboxSize.height;
                viewboxSize.height = viewboxWidth;
            }

            let px = this.boxPosition.x;
            let py = this.boxPosition.y;

            let scale = this.larksr?.currentAppSize ? this.larksr.currentAppSize.width / containerSize.width : 1;

            let box = {
                x: px * scale,
                y: py * scale,
                width: viewboxSize.width * scale,
                height: viewboxSize.height * scale,
            };

            Log.info("update box " ,  box);

            if (this.larksr.updateAerialview) {
                this.larksr.updateAerialview(box);
            }

            this.start = false;
        },
        onHide() {
            this.toggleAerailView();
        },
        onClose() {
            this.larksr.stopAerialview();
            this.toggleAerailView();
        },
        ...mapActions({
            toast: "toast/toast",
            notify: "notifyBar/notify",
            alert: "modalAlert/showModalAlert",
            toggleAerailView: 'toggleAerailView',
        }),
    },
    mounted() {
        Log.info('aerial view mounted', this.larksr);

        let screenOrientation = this.larksr?.screenState.screenOrientation;

        let isLandscape = screenOrientation === 'landscape';

        let containerSize = this.$refs["aerial-view-container"].getBoundingClientRect();
        let viewboxSize = this.$refs["aerial-view-box"].getBoundingClientRect();

        if (isLandscape) {
            const containerWidth = containerSize.width;
            containerSize.width = containerSize.height;
            containerSize.height = containerWidth;

            const viewboxWidth = viewboxSize.width;
            viewboxSize.width = viewboxSize.height;
            viewboxSize.height = viewboxWidth;
        }

        if (!this.larksr) {
            Log.warn("larksr not inited");
            return;
        }

        let scale = this.larksr.currentAppSize.width / containerSize.width;

        let asp = this.larksr.currentAppSize.height / this.larksr.currentAppSize.width;

        containerSize.height = asp * containerSize.width;
        viewboxSize.height = asp * viewboxSize.width;


        Log.info('aerial view mounted', this.larksr.currentAppSize, asp, containerSize, viewboxSize);

        if (this.larksr.startAerialview) {
            this.larksr.startAerialview({
                    x: 0,
                    y: 0,
                    width: viewboxSize.width * scale,
                    height: viewboxSize.height * scale,
                }, 1000, containerSize.width, containerSize.height);
        }

        this.containerSize = {
            width: containerSize.width,
            height: containerSize.height,
        };
        this.boxSize = {
            width: viewboxSize.width,
            height: viewboxSize.height,
        };

        this.larksr.on("aerialviewscreen", (e) => {
            // Log.info("on aerialviewscreen", e, {"background-image": "url(" + e.data + ")" });
            // $("#aerial-view-container").css({"background-image": "url(" + e.data + ")" });
            this.backgroundImage = e.data;
        })
    }
}
</script>
<style lang="scss" scoped>
@import "aerial_view.scss";
</style>
