// ui-react/src/components/notify/notify.jsx
import './notify.scss';
import Btn from '../button/button';
import Log from '@/utils/log';
import CloseImg from '@/assets/images/close.svg';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect, useState } from 'react';
import { clearNotify } from '../../store/modules/notify';

export default function Notify() {
  const dispatch = useDispatch();

  const ui = useSelector(state => state.comm.ui);
  const larksr = useSelector(state => state.comm.larksr);
  const notify = useSelector(state => state.notify.notify);

  const [container, setContainer] = useState({});
  useEffect(() => {
    const val = larksr ? larksr.screenState.container : {
      marginTop: 0, marginLeft: 0, width: 1920, height: 1080
    }
    setContainer(val);
  }, [larksr]);

  const [style, setStyle] = useState({});
  useEffect(() => {
    setStyle({
      width: container.width + 'px',
      marginTop: container + 'px',
      marginLeft: commore.container.marginLeft + 'px',
  })
  }, []);

  // const onClose = () => {
  //   Log.info('close notify bar');
  // };

  const clearNotifyFn = () => {
    dispatch(clearNotify());
  }

  
  const [timer, setTimer] = useState(null);
  useEffect(() => {
    if(notify.show===true) {
      const timeout/*: number*/ = notify.timeout ? notify.timeout : 5000;

      const t = window.setTimeout(() => {
				dispatch(clearNotify());
			}, timeout);
      setTimer(t);
    }

    return() => {
      if(timer) clearTimeout(timer);
    };
  }, [notify]);
  return(
    <div className="notifybar" style={style}>
        <div className="alertInfo">
            [{notify.level}]:{notify.msg}
        </div>
        <Btn 
            info={ui.buttonClose}
            src={CloseImg}
            click={clearNotifyFn}
        />
    </div>
  )
}

// ui-vue3/src/components/notify/notify.vue
<template>
    <div class="notifybar" v-bind:style="style">
        <div class="alertInfo">
            [{{notify.level}}]:{{notify.msg}}
        </div>
        <Btn 
            :info="ui.buttonClose"
            v-bind:src="CloseImg"
            v-on:click="clearNotify"
        />
    </div>
</template>
<script setup>
import { useCommStore } from '@/stores/comm.js';
import { useNotifyBarStore } from '@/stores/notifybar.js';
import Btn from '../button/button.vue';
import Log from '@/utils/log';
import CloseImg from '@/assets/images/close.svg';

const commStore = useCommStore();
const notifyBarStore = useNotifyBarStore();

const ui = computed(() => commStore.ui);
const notify = computed(() => notifyBarStore.notify);

const style = computed(() => {
    const res = {
        width: commStore.container.width + 'px',
        marginTop: commStore.container + 'px',
        marginLeft: commStore.container.marginLeft + 'px',
    };
    return res;
})

const onClose = () => {
    Log.info('close notify bar');
};

const clearNotifyFn = () => {
    store.commit('notifyBar/clearNotify' )
}

</script>
<style lang="scss" scoped>
@import "notify.scss";
</style>
