// ui-mobile-vue-new/src/components/alert/alert.vue
<template>
    <div class="modalAlertPanel" v-bind:style="viewPortStyle">
        <div class="container">
            <div class="container-title">
                <div>
                    <p>{{ ui.tip }}</p>
                </div>
            </div>
            <div class="content">
                <p>{{modalAlert.des}}</p>
            </div>
            <div class="modalConfirmPanel-divider"></div>
            <div class="button-group">
                <Btn :title="ui.buttonSubmit" submit="true" v-on:click="onSubmit" />
            </div>
        </div>
    </div>
</template>
<script>
import Btn        from '../button/button';
import {
    mapState,
    mapGetters,
}                 from 'vuex'

export default {
    name: 'ModalAlert',
    components: { Btn },
    computed: {
        ...mapState({
            ui: state => state.ui,
            modalAlert: state => state.modalAlert.modalAlert
        }),
        ...mapGetters([
            'viewPortStyle'
        ]),
    },
    methods: {
        onSubmit() {
            if (this.modalAlert.callback) {
                this.modalAlert.callback();
            }
            this.$store.commit('modalAlert/reset')
        },
        onKeyup(e) {
            if (e.key == 'Enter') {
                this.onSubmit();
            }
        }
    },
    mounted() {
        document.addEventListener('keyup', this.onKeyup);
    },
    beforeDestroy() {
        document.removeEventListener('keyup', this.onKeyup);
    },
}
</script>
<style lang="scss" scoped>
@import "alert.scss";
</style>

// ui-react/src/components/alert/alert.jsx
import './alert.scss';
import { useDispatch, useSelector } from 'react-redux';
import Btn from '../button/button';
// UI组件
export default function Alert() {

  const dispatch = useDispatch();
  const onSubmit = () => {
    if (modalAlert.callback) {
        modalAlert.callback();
    }
    console.log('callback', modalAlert.callback)
    // dispatch(reset());
}

  const larksr = useSelector(state => state.comm.larksr);
  const modalAlert = useSelector(state => state.alert.modalAlert);
  const ui = useSelector(state => state.comm.ui);
  
  return (
    <div className="modalAlertPanel" style={{width: larksr?.screenState.viewPort.width, height: larksr?.screenState.viewPort.height}}>
      <div className="container">
        <div className="container-title">
          <div>
            <p>{ ui?.tip }</p>
          </div>
        </div>
        <div className="content">
          <p>{modalAlert.des}</p>
        </div>
        <div className="modalConfirmPanel-divider"></div>
        <div className="button-group">
          <Btn title={ui?.buttonSubmit} submit={true} click={onSubmit} />
        </div>
      </div>
    </div>
  )
}
