// ui-vue3/src/components/alert/alert.vue
<template>
    <div class="modalAlertPanel" :style="commStore.viewPortStyle">
        <div class="container">
            <div class="container-title">
                <div>
                    <p>{{ commStore.ui.tip }}</p>
                </div>
            </div>
            <div class="content">
                <p>{{modalAlertStore.modalAlert.des}}</p>
            </div>
            <div class="modalConfirmPanel-divider"></div>
            <div class="button-group">
                <Btn :title="commStore.ui.buttonSubmit" submit="true" v-on:click="onSubmit" />
            </div>
        </div>
    </div>
</template>
<script setup>
import Btn        from '../button/button.vue';
import { useCommStore } from '@/stores/comm';
import { useModalAlertStore } from '@/stores/modal_alert';

const commStore = useCommStore();
const modalAlertStore = useModalAlertStore();

// const modalAlert = computed(() => store.state.modalAlert.modalAlert);
const viewPortStyle = computed(() => store.state.viewPortStyle);

const onSubmit = () => {
    if (modalAlertStore.modalAlert.callback) {
        modalAlertStore.modalAlert.callback();
    }
    modalAlertStore.reset();
};
const onKeyup = (e) => {
    if (e.key == 'Enter') {
        onSubmit();
    }
};

onMounted(() => {
    document.addEventListener('keyup', onKeyup);
})

onUnmounted(() => {
    document.removeEventListener('keyup', onKeyup);
})
</script>
<style lang="scss" scoped>
@import "alert.scss";
</style>

// ui-react/src/components/alert/alert.jsx
import './alert.scss';
import { useDispatch, useSelector } from 'react-redux';
import Btn from '../button/button';
// UI组件
export default function Alert() {

  const dispatch = useDispatch();
  const onSubmit = () => {
    if (modalAlert.callback) {
        modalAlert.callback();
    }
    console.log('callback', modalAlert.callback)
    // dispatch(reset());
}

  const larksr = useSelector(state => state.comm.larksr);
  const modalAlert = useSelector(state => state.alert.modalAlert);
  const ui = useSelector(state => state.comm.ui);
  
  return (
    <div className="modalAlertPanel" style={{width: larksr?.screenState.viewPort.width, height: larksr?.screenState.viewPort.height}}>
      <div className="container">
        <div className="container-title">
          <div>
            <p>{ ui?.tip }</p>
          </div>
        </div>
        <div className="content">
          <p>{modalAlert.des}</p>
        </div>
        <div className="modalConfirmPanel-divider"></div>
        <div className="button-group">
          <Btn title={ui?.buttonSubmit} submit={true} click={onSubmit} />
        </div>
      </div>
    </div>
  )
}
