// ui-react/src/components/confirm/confirm.jsx
import './confirm.scss';
import { useSelector, useDispatch } from 'react-redux';
import { CloseOutlined } from '@ant-design/icons';
import Btn from '../button/button';
import Log from '@/utils/log';
import { reset } from '@/store/modules/confirm';
import { useEffect } from 'react';



export default function Confirm() {
  const dispatch = useDispatch();

  const ui = useSelector(state => state.comm.ui);
  const modalConfirm = useSelector(state => state.confirm.modalConfirm);
  const larksr = useSelector(state => state.comm.larksr);

  const onCancel = () => {
    Log.info('onCancel');
    if (modalConfirm.onCancel) {
        modalConfirm.onCancel();
    }
    dispatch(reset());
  };
  const onSubmit = () => {
      Log.info('onSubmit');
      if (modalConfirm.onSubmit) {
          modalConfirm.onSubmit();
      }
      dispatch(reset());
  };
  const onKeyup = (e) => {
    if (e.key == 'Enter') {
        onSubmit();
    }
  }

  useEffect(() => {
    document.addEventListener('keyup', onKeyup);
    return () => {
      document.removeEventListener('keyup', onKeyup);
    }
  }, [])
  return (
    <div className="modalConfirmPanel" style={{width: larksr?.screenState.viewPort.width, height: larksr?.screenState.viewPort.height}}>
        <div className="container">
            <div className="modalConfirmPanel-title">
                <div>
                    <p>{modalConfirm.title}</p>
                </div>
                <div onClick={onCancel}>
                  <CloseOutlined />
                </div>
            </div>
            <div className="content">
                <p>{modalConfirm.des}</p>
            </div>
            <div className="modalConfirmPanel-divider"></div>
            <div className="button-group">
                <Btn className="submit" title={ui.buttonSubmit} submit={false} click={onSubmit}/>
                <Btn className="cancel" title={ui.buttonCancel} submit={false} click={onCancel} />
            </div>
        </div>
    </div>
  )
}

// ui-mobile-vue-new/src/components/confirm/confirm.vue
<template>
    <div class="modalConfirmPanel" v-bind:style="viewPortStyle">
        <div class="container">
            <div class="modalConfirmPanel-title">
                <div>
                    <p>{{modalConfirm.title}}</p>
                </div>
                <div v-on:click="onCancel">
                    <i class="el-icon-close"></i>
                </div>
            </div>
            <div class="content">
                <p>{{modalConfirm.des}}</p>
            </div>
            <div class="modalConfirmPanel-divider"></div>
            <div class="button-group">
                <Btn class="submit" :title="ui.buttonSubmit" submit="false" v-on:click="onSubmit" />
                <Btn class="cancel" :title="ui.buttonCancel" submit="false" v-on:click="onCancel" />
            </div>
        </div>
    </div>
</template>
<script>
import Btn        from '../button/button';
import Log        from '@/utils/log';
import {
    mapState,
    mapGetters,
}                 from 'vuex'

export default {
    name: 'ModalAlert',
    components: { Btn },
    computed: {
        ...mapState({
            ui: state => state.ui,
            modalConfirm: state => state.modalConfirm.modalConfirm,
        }),
        ...mapGetters([
            'viewPortStyle'
        ]),
    },
    methods: {
        onCancel() {
            Log.info('onCancel');
            if (this.modalConfirm.onCancel) {
                this.modalConfirm.onCancel();
            }
            this.$store.commit('modalConfirm/reset');
        },
        onSubmit() {
            Log.info('onSubmit');
            if (this.modalConfirm.onSubmit) {
                this.modalConfirm.onSubmit();
            }
            this.$store.commit('modalConfirm/reset');
        },
        onKeyup(e) {
            if (e.key == 'Enter') {
                this.onSubmit();
            }
        }
    },
    mounted() {
        document.addEventListener('keyup', this.onKeyup);
    },
    beforeDestroy() {
        document.removeEventListener('keyup', this.onKeyup);
    },
}
</script>
<style lang="scss" scoped>
@import "confirm.scss";
</style>
