// ui-react/src/components/micInput/micInput.jsx
import './micInput.scss';
import Log from "@/utils/log";
import Tooltip from '../menuBar/components/tooltip';
import { useEffect, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { toastAct } from '../../store/modules/toast';
import { DownOutlined, UpOutlined } from '@ant-design/icons';

export default function MicInput() {
  const dispatch = useDispatch();

  const larksr = useSelector(state => state.comm.larksr);
  const ui = useSelector(state => state.comm.ui);
  const isMobile = useSelector(state => state.comm.isMobile);
  const menubarPosition = useSelector(state => state.comm.menubarPosition);

  
  const [audioTrackEnableManu, setAudioTrackEnableManu] = useState(false);
  const [setupPanel, setSetupPanel] = useState(false);
  const [selecteDevice, setSelecteDevice] = useState('');
  const [devices, setDevices] = useState([]);

  const [containerClass, setContainerClass] = useState('');
  useEffect(() => {
    isMobile ? setContainerClass('mic-input mic-input-mobile') : setContainerClass('mic-input');
  }, [isMobile]);

  const [audioInput, setAudioInput] = useState(false);
  const [audioDeviceId, setAudioDeviceId]= useState('');
  const [audioTrack, setAudioTrack]= useState(null);
  const [audioPaused, setAudioPaused] = useState(false);
  useEffect(() => {
    setAudioInput(larksr?.params.audioInput);
    setAudioDeviceId(larksr?.audioDeviceId);
    setAudioTrack(larksr?.audioTrack);
    setAudioPaused(larksr?.audioPaused);
  }, [larksr])


  const [audioTrackEnable, setAudioTrackEnable] = useState(false);
  const [manuSetAudioTrackEnable, setManuSetAudioTrackEnable] = useState(false);
  useEffect(() => {
    if (manuSetAudioTrackEnable) {
      setAudioTrackEnable(audioTrackEnableManu);
    } else {
      setAudioTrackEnable(!audioPaused);
    }
  }, [manuSetAudioTrackEnable, audioTrackEnableManu, audioPaused]);



  const micCheck = (row) => {
    setSelecteDevice(row.deviceId);
    if(!audioPaused) { // 音频开启状态
        if(larksr.audioDeviceId !== selecteDevice) {
            larksr?.closeAudio();
            openAudio();
        }
    }
  };

  // const onAudioTrackEnable = (e) => {
  //     Log.info('audio track enable', e);
  // };
  const openAudio = () => {
      Log.info('openAudio with device ', selecteDevice);
      larksr.openAudio(selecteDevice)
      .then((res) => {
          Log.info("open audio success", res, audioTrack, selecteDevice);
          setAudioTrackEnable(!audioPaused);
      })
      .catch((e) => {
          Log.warn("open audio failed.", e);
          if (window.location.href.indexOf("https") == -1) {
            dispatch(toastAct({text: ui.audioUseHttps, position: 1, level: 3}));
          } else {
            dispatch(toastAct( { text: JSON.stringify(e), position: 1, level: 3 }));
          }
      });
  };
  const toggleMic = () => {
      Log.info("toggleMic", audioDeviceId);
      if (setupPanel) setSetupPanel(false);
      if(!audioPaused) { // 音频开启状态
          larksr?.closeAudio();
          setAudioTrackEnableManu(!audioPaused);
      } else { // 音频关闭状态
          openAudio();
      }
  };
  const toggleSetupPanel = () => {
    setSetupPanel(!setupPanel); 
    if (setupPanel && larksr) {
        larksr.getConnectedAudioinputDevices()
        .then((res) => {
            Log.info("audio devices", res);
            setDevices(res);
            if (!selecteDevice) {
              setSelecteDevice(res[0].deviceId);
            }
        })
        .catch((e) => {
            Log.warn("no audio device found ", e);
        })
    }
  };

  return(
    <div>
      { audioInput && 
        <div className={containerClass}>
          <Tooltip
            title={<span>{ui.mic}</span>}
            content={
              <div>
                {audioTrackEnable?
                  <div className="menu-icon"  onClick={toggleMic}>
                      <i className="iconfont icon-mic_1 icon-click"></i>
                  </div>
                  :
                  <div className="menu-icon"  onClick={toggleMic}>
                      <i className="iconfont icon-mic"></i>
                  </div>
                }
              </div>
            }
          >
          </Tooltip>
          { setupPanel? <DownOutlined  onClick={toggleSetupPanel}/> : <UpOutlined  onClick={toggleSetupPanel}/>}
          {
            setupPanel &&
            <div className={`setup${menubarPosition==='top'? ' top': (menubarPosition==='bottom'? ' bottom': '')}`}>
              <p className="setup-title">{ ui.selectMic }</p>
              {
                devices.length?
                devices.map(device => {
                  return <div onClick={() => micCheck(device)} className="setup-row" key={device.deviceId}>
                            <span> { device.label }</span>
                            {selecteDevice === device.deviceId && <i className="el-icon-check"></i>}
                          </div>
                })
                :
                <div className="setup-row">
                  <span>{ ui.nothing }</span>
                </div>
              }
            </div>
          }
        </div>
      }
    </div>
  )
}

// ui-vue3/src/components/mic_input/mic_input.vue
<template>
    <div :class="containerClass"  v-if="audioInput">
        <Tooltip>
            <template #title>{{ ui.mic }}</template>
            <div v-if="audioTrackEnable" class="menu-icon"  @click="toggleMic">
                <i class="iconfont icon-mic_1 icon-click"></i>
            </div>
            <div v-else class="menu-icon"  @click="toggleMic">
                <i class="iconfont icon-mic"></i>
            </div>
        </Tooltip>
        <el-icon v-if="setupPanel" @click="toggleSetupPanel"><ArrowDown /></el-icon>
        <el-icon v-else  @click="toggleSetupPanel"><ArrowUp /></el-icon>
        <div v-if="setupPanel" :class="{'setup':true, 'top': menubarPosition==='top','bottom': menubarPosition==='bottom'}">
            <p class="setup-title">{{ ui.selectMic }}</p>
            <template v-if="devices.length">
                <div v-for="(device, key) in devices" @click="micCheck(device)" class="setup-row" :key="key">
                    <span> {{ device.label }}</span>
                    <el-icon v-if="selecteDevice === device.deviceId"><Check /></el-icon>
                </div>
            </template>
            <template v-else>
                <div class="setup-row">
                    <span>{{ ui.nothing }}</span>
                </div>
            </template>
        </div>
    </div>
</template>
<script setup>
import { useCommStore } from '@/stores/comm.js';
import { useToastStore } from '@/stores/toast.js'
import Log from "@/utils/log";
import Tooltip from '../menuBar/components/tooltip.vue';

const commStore = useCommStore();
const toastStore = useToastStore();

const audioTrackEnableManu = ref(false);
const manuSetAudioTrackEnable = ref(false);
const setupPanel = ref(false);
const selecteDevice = ref('');
const devices = reactive({
    list: []
})

const larksr = computed(() => {
    return commStore.larksr;
})
const ui = computed(() => {
    return commStore.ui;
})
const menubarPosition = computed(() => {
    return commStore.menubarPosition;
})

const containerClass = computed(() => {
    return commStore.isMobile ? 'mic-input mic-input-mobile' : 'mic-input';
})

const audioInput = computed(() => {
    return larksr.value?.params.audioInput;
})

const audioDeviceId = computed(() => {
    return larksr.value?.audioDeviceId;
})

const audioTrack = computed(() => {
    return larksr.value?.audioTrack;
})
const audioPaused = computed(() => {
    return larksr.value?.audioPaused;
})
const audioTrackEnable = computed({
    get() {
        if (manuSetAudioTrackEnable.value) {
            return audioTrackEnableManu.value;
        } else {
            return !audioPaused.value;
        }
    },
    set(enable) {
        manuSetAudioTrackEnable.value = true;
        audioTrackEnableManu.value = enable;
    }
})

const micCheck = (row) => {
    selecteDevice.value = row.deviceId;
    if(!audioPaused.value) { // 音频开启状态
        if(larksr.value.audioDeviceId !== selecteDevice.value) {
            larksr.value?.closeAudio();
            openAudio();
        }
    }
};

const onAudioTrackEnable = (e) => {
    Log.info('audio track enable', e);
};
const openAudio = () => {
    Log.info('openAudio with device ', selecteDevice.value);
    larksr.value.openAudio(selecteDevice.value)
    .then((res) => {
        Log.info("open audio success", res, audioTrack.value, selecteDevice.value);
        audioTrackEnable.value = !audioPaused.value;
    })
    .catch((e) => {
        Log.warn("open audio failed.", e);
        if (window.location.href.indexOf("https") == -1) {
            toastStore.toastAct( { text: ui.value.audioUseHttps, position: 1, level: 3 });
        } else {
            toastStore.toastAct( { text: JSON.stringify(e), position: 1, level: 3 });
        }
    });
};
const toggleMic = () => {
    Log.info("toggleMic", audioDeviceId.value);
    if (setupPanel.value) setupPanel.value = false;
    if(!audioPaused.value) { // 音频开启状态
        larksr.value?.closeAudio();
        audioTrackEnable.value = !audioPaused.value;
        // forceUpdate();
    } else { // 音频关闭状态
        openAudio();
    }
};
const toggleSetupPanel = () => {
    setupPanel.value = !setupPanel.value;
    if (setupPanel.value && larksr.value) {
        larksr.value.getConnectedAudioinputDevices()
        .then((res) => {
            Log.info("audio devices", res);
            devices.list = res;
            if (!selecteDevice.value) {
                selecteDevice.value = res[0].deviceId;
            }
        })
        .catch((e) => {
            Log.warn("no audio device found ", e);
        })
    }
};

onMounted(() => {
    Log.info('mic input larksr', larksr.value, audioInput.value);
})
</script>
<style lang="scss" scoped>
@import "mic_input.scss";
</style>
