// ui-react/src/components/button/button.jsx
import { useEffect, useState } from 'react';
import './button.scss';



export default function Btn(props) {

  let {info, title, src, submit } = props;

  const [showInfo, setShowInfo] = useState(false);

  let isShowInfo;
  useEffect(() => {
    isShowInfo = info && showInfo;
  }, [info, showInfo]);

  let titleMode;
  useEffect(() => {
    if (title && src)  titleMode = 1;
    else if (title) titleMode = 2;
    else if (src) titleMode = 3;
    else titleMode = -1;

  }, []);

  const onTouchStart = (e) => {
    props.touchstart && props.touchstart(e)
    setShowInfo(true);
  };
  const onTouchEnd = (e) => {
    props.touchend && props.touchend(e);
    setShowInfo(false);
  };
  const onTouchCancel = (e) => {
    setShowInfo(false);
  };
   const onMouseEnter = () => {
    setShowInfo(true);
  };
  const onMouseLeave = () => {
    setShowInfo(false);
  };
  const onEubmit = () => {
      if (submit) {
        props.click();
        props.submit();
      }
  }
  
  let [content, setContent] = useState(null);
  
  useEffect(() => {
    if(titleMode==1) {
      setContent(<div className="buttonRow">
        <img className="buttonRowCell" src={src} alt=""/>
        <div className="buttonRowCell">{title}</div>
      </div>)
    } else if(titleMode==2) {
      setContent(<div className="button-title">{title}</div>);
    } else if(titleMode==3) {
      setContent(<img src={src} alt="" />);
    } else{
      setContent(<div className="buttonTitle">
                  {props.children}
                </div>);
    }
    
  },[titleMode,title])
  
  return (
    <div className="button" 
        onClick={props.click}
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
        onTouchCancel={onTouchCancel}
        onMouseEnter={onMouseEnter} 
        onMouseLeave={onMouseLeave}
        onKeyUp={onEubmit}
    >
      {isShowInfo && 
        <div className="info">{info}</div>
      }
      {content}
    </div>
  )
}

// ui-mobile-vue/src/components/button/button.vue
<template>
    <div class="button" 
        v-on:click="$emit('click')"
        v-on:touchstart="onTouchStart"
        v-on:touchend="onTouchEnd"
        v-on:touchcancel="onTouchCancel"
        v-on:mouseenter="onMouseEnter" 
        v-on:mouseleave="onMouseLeave"
        v-on:keyup.enter="onEubmit"
    >
        <div v-if="isShowInfo" class="info">{{info}}</div>
        <div v-if="titleMode==1" class="buttonRow">
            <img class="buttonRowCell" v-bind:src="src" alt="">
            <div class="buttonRowCell">{{title}}</div>
        </div>
        <div v-else-if="titleMode==2" class="buttonTitle">
            {{title}} 
        </div>
        <img v-else-if="titleMode==3" v-bind:src="src" alt="" />
        <div v-else class="buttonTitle">
            <slot></slot>
        </div>
    </div>
</template>
<script>
export default {
    name: 'btn',
    props: ['info', 'title', 'src', 'submit'],
    data() {
        return {
            showInfo: false
        }
    },
    computed: {
        isShowInfo() {
            return this.info && this.showInfo;
        },
        titleMode() {
            if (this.title && this.src) 
                return 1;
            else if (this.title)
                return 2;
            else if (this.src)
                return 3;
            else
                return -1;
        }
    },
    methods: {
        onTouchStart(e) {
            this.$emit("touchstart", e);
            this.showInfo = true;
        },
        onTouchEnd(e) {
            this.$emit("touchend", e);
            this.showInfo = false;
        },
        onTouchCancel(e) {
            this.showInfo = false;
        },
        onMouseEnter() {
            this.showInfo = true;
        },
        onMouseLeave() {
            this.showInfo = false;
        },
        onEubmit() {
            if (this.submit) {
                this.$emit('click');
                this.$emit('submit');
            }
        }
    }
}
</script>
<style lang="scss" scoped>
@import "button.scss";
</style>
