// ui-react/src/components/mobile/joystickIndex/key/key.jsx
import { useEffect, useRef, useState } from 'react';
import styles from './key.module.scss';

export default function Key(props) {
  const {circle, size, keyName, start, end,longPress,repeat} = props;

  const [showTip, setShowTip] = useState(false);
  const timeout = useRef(null);
  const [touched, setTouched] = useState(false);
  const [touchStartTime, setTouchStartTime] = useState(0);
  const [longPressed, setLongPressed] = useState(false);

  const [isInput, setIsInput] = useState(false);
  const [keyClass, setKeyClass] = useState("");
  useEffect(() => {
    if (circle) {
      return size ? setKeyClass("key circle ") + size : setKeyClass("key circle");
    } else {
        return size ? setKeyClass("key ") + size : setKeyClass("key");
    }
  }, [circle, size]);

  const onTouchStart = (e) => {
    e.preventDefault();
    e.stopPropagation();
    // Log.info("onTouchStart");
    setShowTip(true);
    setTouched(true);
    setTouchStartTime(Date.now())
    start(keyName);
    timeout.current = window.setTimeout(() => {
      repeatPress();
    }, 500);
  };
  const onTouchEnd = (e) => {
      e.preventDefault();
      e.stopPropagation();
      // Log.info("onTouchEnd");
      setShowTip(false);
      setTouched(false);
      setLongPressed(false);
      if (timeout.current) {
          window.clearTimeout(timeout.current);
      }
      setTouchStartTime(0);
      end(keyName);
  };
  const repeatPress = () => {
      if (touched) {
          // check long press
          if (!longPressed && touchStartTime != 0 && Date.now() - touchStartTime > 2000) {
            setLongPressed(true);
            longPress(keyName);
          }
          timeout.current = window.setTimeout(() => {
              repeat(keyName);
              repeatPress();
          }, 250);
      }
  };
  const onSelect = (e) => {
      e.preventDefault();
      e.stopPropagation();
  };
  return(
    <div className={styles.container}>
      <div className={keyClass}
        onSelectStart={onSelect}
        onTouchStart={onTouchStart} onTouchEnd={onTouchEnd} onTouchCancle={onTouchEnd} >
          {
            (showTip && isInput) &&
            <div className="tip">
              <slot onSelectStart={onSelect}></slot>
            </div>
          }
        {props.content}
      </div>
    </div>
  )
}

// ui-mobile-vue-new/src/components/mobile/keyboard/key/key.vue
<template>
    <div :class="keyClass" 
        v-on:selectstart="onSelect"
        v-on:touchstart="onTouchStart" v-on:touchend="onTouchEnd" v-on:touchcancle="onTouchEnd"
    >
        <div v-if="showTip && isInput" class="tip">
            <slot v-on:selectstart="onSelect"></slot>
        </div>
        <slot></slot>
    </div>
</template>
<script>
export default {
    props: ["circle", "size", "keyName"],
    components: {
    },
    data() {
        return {
            showTip: false,
            timeout: null,
            touched: false,
            touchStartTime: 0,
            longPressed: false,
        }
    },
    computed: {
        isInput() {
            return !this.type || this.type == "input";
        },
        isFunc() {
            return this.type && this.type == "func";
        },
        keyClass() {
            if (this.circle) {
                return this.size ? "key circle " + this.size : "key circle";
            } else {
                return this.size ? "key " + this.size : "key";
            }
        },
    },
    methods: {
        onTouchStart(e) {
            e.preventDefault();
            e.stopPropagation();
            // console.log("onTouchStart");
            this.showTip = true;
            this.touched = true;
            this.touchStartTime = Date.now();
            this.$emit("start", this.keyName);
            this.timeout = window.setTimeout(() => {
                this.repeatPress();
            }, 500);
        },
        onTouchEnd(e) {
            e.preventDefault();
            e.stopPropagation();
            // console.log("onTouchEnd");
            this.showTip = false;
            this.touched = false;
            this.longPressed = false;
            if (this.timeout) {
                window.clearTimeout(this.timeout);
            }
            this.touchStartTime = 0;
            this.$emit("end", this.keyName);
        },
        repeatPress() {
            if (this.touched) {
                // check long press
                if (!this.longPressed && this.touchStartTime != 0 && Date.now() - this.touchStartTime > 2000) {
                    this.longPressed = true;
                    this.$emit("longPress",this.keyName);
                }
                this.timeout = window.setTimeout(() => {
                    this.$emit("repeat", this.keyName);
                    this.repeatPress();
                }, 250);
            }
        },
        onSelect(e) {
            e.preventDefault();
            e.stopPropagation();
        },
    }
}
</script>
<style lang="scss" scoped>
@import 'key.scss';
</style>
