// ui-react/src/components/mobile/joystickIndex/key/key.jsx
import { useEffect, useRef, useState } from 'react';
import styles from './key.module.scss';

export default function Key(props) {
  const {circle, size, keyName, start, end,longPress,repeat} = props;

  const [showTip, setShowTip] = useState(false);
  const timeout = useRef(null);
  const [touched, setTouched] = useState(false);
  const [touchStartTime, setTouchStartTime] = useState(0);
  const [longPressed, setLongPressed] = useState(false);

  const [isInput, setIsInput] = useState(false);
  const [keyClass, setKeyClass] = useState("");
  useEffect(() => {
    if (circle) {
      return size ? setKeyClass("key circle ") + size : setKeyClass("key circle");
    } else {
        return size ? setKeyClass("key ") + size : setKeyClass("key");
    }
  }, [circle, size]);

  const onTouchStart = (e) => {
    e.preventDefault();
    e.stopPropagation();
    // Log.info("onTouchStart");
    setShowTip(true);
    setTouched(true);
    setTouchStartTime(Date.now())
    start(keyName);
    timeout.current = window.setTimeout(() => {
      repeatPress();
    }, 500);
  };
  const onTouchEnd = (e) => {
      e.preventDefault();
      e.stopPropagation();
      // Log.info("onTouchEnd");
      setShowTip(false);
      setTouched(false);
      setLongPressed(false);
      if (timeout.current) {
          window.clearTimeout(timeout.current);
      }
      setTouchStartTime(0);
      end(keyName);
  };
  const repeatPress = () => {
      if (touched) {
          // check long press
          if (!longPressed && touchStartTime != 0 && Date.now() - touchStartTime > 2000) {
            setLongPressed(true);
            longPress(keyName);
          }
          timeout.current = window.setTimeout(() => {
              repeat(keyName);
              repeatPress();
          }, 250);
      }
  };
  const onSelect = (e) => {
      e.preventDefault();
      e.stopPropagation();
  };
  return(
    <div className={styles.container}>
      <div className={keyClass}
        onSelectStart={onSelect}
        onTouchStart={onTouchStart} onTouchEnd={onTouchEnd} onTouchCancle={onTouchEnd} >
          {
            (showTip && isInput) &&
            <div className="tip">
              <slot onSelectStart={onSelect}></slot>
            </div>
          }
        {props.content}
      </div>
    </div>
  )
}

// ui-vue3/src/components/mobile/keyboard/key/key.vue
<template>
    <div :class="keyClass" 
        v-on:selectstart="onSelect"
        v-on:touchstart="onTouchStart" v-on:touchend="onTouchEnd" v-on:touchcancle="onTouchEnd" >
        <div v-if="showTip && isInput" class="tip">
            <slot v-on:selectstart="onSelect"></slot>
        </div>
        <slot></slot>
    </div>
</template>
<script setup>

const props = defineProps(["circle", "size", "keyName"]);

const showTip = ref(false);
const timeout = ref(null);
const touched = ref(false);
const touchStartTime = ref(0);
const longPressed = ref(false);

const isInput = computed(() => {
    return !this.type || this.type == "input";
})

const keyClass = computed(() => {
    if (props.circle) {
        return props.size ? "key circle " + props.size : "key circle";
    } else {
        return props.size ? "key " + props.size : "key";
    }
});
const emits = defineEmits(['start', 'end','longPress','repeat'])
const onTouchStart = (e) => {
    e.preventDefault();
    e.stopPropagation();
    // Log.info("onTouchStart");
    showTip.value = true;
    touched.value = true;
    touchStartTime.value = Date.now();
    emits("start", props.keyName);
    timeout.value = window.setTimeout(() => {
        repeatPress();
    }, 500);
};
const onTouchEnd = (e) => {
    e.preventDefault();
    e.stopPropagation();
    // Log.info("onTouchEnd");
    showTip.value = false;
    touched.value = false;
    longPressed.value = false;
    if (timeout.value) {
        window.clearTimeout(timeout.value);
    }
    touchStartTime.value = 0;
    emits("end", props.keyName);
};
const repeatPress = () => {
    if (touched.value) {
        // check long press
        if (!longPressed.value && touchStartTime.value != 0 && Date.now() - touchStartTime.value > 2000) {
            longPressed.value = true;
            emits("longPress",props.keyName);
        }
        timeout.value = window.setTimeout(() => {
            emits("repeat", props.keyName);
            repeatPress();
        }, 250);
    }
};
const onSelect = (e) => {
    e.preventDefault();
    e.stopPropagation();
};
</script>
<style lang="scss" scoped>
@import 'key.scss';
</style>
