// ui-react/src/components/playerMode/playerMode.jsx
import './playerMode.scss';
import { PlayerModeType, UserType, setShowPlayerList } from '../../store/modules/playerMode';
import { useEffect, useRef, useState } from 'react';
import { CloseOutlined, DownOutlined, UpOutlined } from '@ant-design/icons';
import { useDispatch, useSelector } from 'react-redux';
import Load from '@/load';
import Log from '@/utils/log';
import clipboard from 'clipboard';

export default function PlayerMode() {
  const dispatch = useDispatch();
  
  const larksr = useSelector(state => state.comm.larksr);
  const ui = useSelector(state => state.comm.ui);
  const isMobile = useSelector(state => state.comm.isMobile);
  const playerMode = useSelector(state => state.comm.playerMode);

  const [copyAuthCodeBtn, setCopyAuthCodeBtn] = useState(null);
  const [copyBtn, setCopyBtn] = useState(null);
  const [showShare, setShowShare] = useState(false);
  const [showPlayerBox, setShowPlayerBox] = useState(true);

  const showShareBtn = true;
  const [alertPositionStyle, setAlertPositionStyle] = useState({});
  useEffect(() => {
    if(isMobile) {
      setAlertPositionStyle({
        top: '10%',
        // transform: 'translateY(-50%)',
        left: '1.89rem'
      });
  } else {
    setAlertPositionStyle({
      top: '75px',
      right: '20px',
      // position: 'absolute'
    })
  }
  }, [isMobile]);

  const [isInteractiveMode, setIsInteractiveMode] = useState(null);
  const [isPlayer, setIsPlayer] = useState(false);
  const [isTaskOwner, setIsTaskOwner] = useState(false);
  const [copyShareAuthCodeText, setCopyShareAuthCodeText] = useState('');

  useEffect(() => {
    setIsPlayer(playerMode.userType == UserType.Player);
    setIsTaskOwner(playerMode.isTaskOwner);
    setCopyShareAuthCodeText(playerMode.authCode ? ui.playerCopy : "");
  }, [playerMode])

  useEffect(() => {
    setIsInteractiveMode(larksr?.isInteractiveMode)
  }, [larksr]);

  const [playerModeStr, setPlayerModeStr] = useState('');
  useEffect(() => {
    setPlayerModeStr(isInteractiveMode ? ui.playerModeInteractive : ui.playerModeNormal)
  }, [isInteractiveMode]);

  const [userTypeStr, setUserTypeStr] = useState('');
  useEffect(() => {
    setUserTypeStr(isPlayer ? ui.userTypePlayer : ui.userTypeObserver)
  }, [isPlayer]);

  const [taskOwnerStr, setTaskOwnerStr] = useState('');
  useEffect(() => {
    setTaskOwnerStr(isTaskOwner ? ui.playerOwner : "")
  }, [isTaskOwner]);

  const [shareUrl, setShareUrl] = useState('');
  useEffect(() => {
    if (!larksr) {
      return "";
    }
    const { params } = larksr;
    let path = import.meta.env.MODE === "dev"? '/webclient': '/webclient/' ;
    // Log.info("larksr params", params);
    let shareUrl = "";

    // 防止刷新url
    const urlBase = import.meta.env.MODE === 'prod' ? window.location.origin : import.meta.env.VITE_APP_API_URL;
    let searchUrl = "";

    searchUrl += "appliId=" + params.appliId + "&";

    if (params.authCode && params.authCode != 'null') {
        searchUrl += "authCode=" + params.authCode + "&";
    } else if (Load.authCode && Load.authCode != 'null') {
        searchUrl += "authCode=" + Load.authCode + "&";
    } else {
        searchUrl += "taskId=" + params.taskid + "&";
    }

    searchUrl += "codeRate=" + params.codeRate + "&";
    searchUrl += "frameRate=" + params.frameRate + "&";

    if (params.groupId && params.groupId != 'null') {
        searchUrl += "groupId=" + params.groupId + "&";
    }
    if (Load.accessType && Load.accessType != '') {
        searchUrl += "accessType=" + Load.accessType + "&";
    }
    if (Load.shareId && Load.shareId != '') {
        searchUrl += "shareId=" + Load.shareId + "&";
    }


    searchUrl += "wsProxy=" + params.wsProxy + "&";
    // only ob
    searchUrl += "playerMode=" + params.playerMode + "&userType=0";

    shareUrl = urlBase + path + "?" + searchUrl;

    // Log.info("share url", shareUrl);
    setShareUrl(searchUrl);
  }, [larksr]);

  const [playerModeClass, setPlayerModeClass] = useState('');
  const showPlayerList = useSelector(state => state.playerMode.showPlayerList);
  useEffect(() => {
    if (showPlayerList && isInteractiveMode) {
      setPlayerModeClass("playerMode mobile");
  } else {
    setPlayerModeClass("playerMode hide");
  }
  }, [showPlayerList, isInteractiveMode]);

  const authCode = useSelector(state => state.playerMode.authCode);
  const playerList = useSelector(state => state.playerMode.playerList);
  const copyAuthcodeButtonRef = useRef(null);
  const copyBtnRef = useRef(null);

  const onClose = () => {
    Log.info('onClose');
    dispatch(setShowPlayerList(false));
  };

  // 方法
  const onSelectItem = (index) => {
    const player = playerMode.playerList[index];
    Log.info('onSelectItem', index, player);
    if (playerMode.playerModeType == PlayerModeType.MutiPlayer) {
        Log.info("MutiPlayer mode no change.");
        return;
    }
    if (!isTaskOwner) {
        dispatch(toastAct( {text: ui.playerNotOwner, position: 2}));
    } else {
        if (player.userType == UserType.Player) {
          dispatch(toastAct( {text: ui.playerAlready, position: 2}));
        } else {
          dispatch(toastAct( {text: ui.playerChanging, position: 2}));
            if (larksr) {
                larksr.changeOperater(player.userId);
            }
        }
    }
  };
  // const toggleShareButton = () => {
  //   showShare = !showShare;
  // };

  useEffect(() => {
    Log.info('clipboard', clipboard);
    Log.info('show player mode', playerMode);
    if (isPlayer) {
        Log.info("is player. set share href to ob.");
    }

    // init share button
    if (!copyBtn) {
        if (copyBtnRef.current) {
          setCopyBtn(new clipboard(copyBtnRef.current))
            // copyBtn = ;
        }
        Log.info("copy btn ", copyBtn, copyBtnRef.current,  shareUrl);
        if (copyBtn) {
            copyBtn.on('success', (e) => {
                Log.info("copy ", e.text);
                e.clearSelection();
                dispatch(toastAct( {text: ui.playerCopyShareUrl, position: 2}));
            });

            copyBtn.on('error', (e) => {
              dispatch(toastAct( {text: ui.playerCopyShareUrlFailed, position: 2}));
            });
        }
    }

    // copy authCode
    if (!copyAuthCodeBtn) {
        if (copyAuthcodeButtonRef.current) {
          setCopyAuthCodeBtn(new clipboard(copyAuthcodeButtonRef.current));
        }
        Log.info("copy room code btn ", copyAuthCodeBtn, copyAuthcodeButtonRef.current, playerMode.authCode);
        if (copyAuthCodeBtn) {
            copyAuthCodeBtn.on('success', (e) => {
                Log.info("copy ", e.text, e);
                e.clearSelection();
                dispatch(toastAct( {text: ui.playerCopyAuthCodeSuccess, position: 2}));
            });

            copyAuthCodeBtn.on('error', (e) => {
              dispatch(toastAct( {text: ui.playerCopyAuthCodeFailed, position: 2}));
            });
        }
    }

    return() => {
      setCopyAuthCodeBtn(null);
      setCopyBtn(null);
    }
  }, []);

  return (
    <div className={playerModeClass} style={alertPositionStyle}>
        <div className={`windowBar${!showPlayerBox?' windowBar-hide': ''}`}>
            <div className="authCode">
              {
                authCode?
                <div>
                  <input type="text" id="authCode" value="authCode" readOnly={true} />
                  <i className="iconfont" ref={copyAuthcodeButtonRef} data-clipboard-target="#authCode">&#xe61b;</i>
                </div>
                :
                <span>{ ui.showPlayerTtile }</span>
              }
              { showShareBtn && <i style={{'marginLeft': '1rem'}} className="iconfont" ref={copyBtnRef} data-clipboard-target="#shareUrl">&#xe621;</i>}
                
            </div>
            <div className="close">
              { (isMobile && showPlayerBox) && <DownOutlined onClick={() => { setShowPlayerBox(!showPlayerBox); }} />}
              { (isMobile && !showPlayerBox) && <UpOutlined onClick={() => { setShowPlayerBox(!showPlayerBox); }} />}
              <CloseOutlined onClick={onClose} />
            </div>
        </div>
        {
          showPlayerBox &&
          <div className="player-box">
            <div className="player-row">
                <span className="number">{ ui.playerNumber }</span>
                <span className="nickname">{ ui.playerNickname }</span>
                <span className="role">{ ui.playerRole }</span>
                <span className="authority">{ ui.playerAuthority }</span>
            </div>
            {
              playerList.map((item, index) => {
                return <div className={`player-row${item.isCurrent?' check-color':'' }`}   key={index} onClick={() => onSelectItem(index)}>
                  <span className="number">{item.userId}</span>
                  <span className="nickname">{item.nickName}</span>
                  <span className="role">
                    {
                      isTaskOwner?
                      <i className="iconfont icon-guanliyuan"></i>:
                      <i className="iconfont icon-yonghu"></i>
                    }
                  </span>
                  <span className="authority">
                    { item.userType == 1 && <i className="iconfont icon-Touch"></i>}
                  </span>
              </div>
              })
            }
            
            <input style={{'opacity': 0,'zIndex': -1}} type="text" id="shareUrl" value={shareUrl} readOnly={true} />
        </div>
        }
        

    </div>
  )
}

// ui-mobile-vue-new/src/components/player_mode/player_mode.vue
<template>
    <div :class="playerModeClass" :style="alertPositionStyle">
        <div :class="{'windowBar': true, 'windowBar-hide': !showPlayerBox}">
            <div class="authCode">
                <template v-if="playerMode.authCode">
                    <input type="text" id="authCode" :value="playerMode.authCode" readonly="true" />
                    <i class="iconfont" ref="copy-authcode-button" data-clipboard-target="#authCode">&#xe61b;</i>
                </template>
                <template v-else>
                    <span>{{ ui.showPlayerTtile }}</span>
                </template>
                <i v-if="showShareBtn" style="margin-left: 1rem;" class="iconfont" ref="copyBtn" data-clipboard-target="#shareUrl">&#xe621;</i>
            </div>
            <div class="close">
                <i v-if="isMobile" :class="showPlayerBox?'el-icon-arrow-down flod-icon':'el-icon-arrow-up flod-icon'" @click="showPlayerBox = !showPlayerBox"></i>
                <i class="el-icon-close" @click="onClose"></i>
            </div>
        </div>
        <div v-show="showPlayerBox" class="player-box">
            <div class="player-row">
                <span class="number">{{ ui.playerNumber }}</span>
                <span class="nickname">{{ ui.playerNickname }}</span>
                <span class="role">{{ ui.playerRole }}</span>
                <span class="authority">{{ ui.playerAuthority }}</span>
            </div>
            <div :class="{'player-row': true, 'check-color':item.isCurrent }"  v-for="(item, index) in playerMode.playerList" :key="index" v-on:click="onSelectItem(index)">
                <span class="number">{{item.userId}}</span>
                <span class="nickname">{{item.nickName}}</span>
                <span class="role">
                    <i v-if="item.isTaskOwner" class="iconfont icon-guanliyuan"></i>
                    <i v-else class="iconfont icon-yonghu"></i>
                </span>
                <span class="authority">
                    <i v-if="item.userType == 1" class="iconfont icon-Touch"></i>
                </span>
            </div>
            <input style="opacity: 0;z-index: -1;" type="text" id="shareUrl" :value="shareUrl" readonly="true">
        </div>

    </div>
</template>
<script>
import {
    mapState,
    mapActions, mapMutations
}                                    from 'vuex'
import {
    PlayerModeType,
    UserType
}                                    from '@/store/modules/player_mode'
import Log                           from '@/utils/log';
import clipboard                     from 'clipboard';
import Load                          from '@/load';

export default {
    data() {
        return {
            copyAuthCodeBtn: null,
            copyBtn: null,
            showShare: false,
            showPlayerBox: true
        }
    },
    computed: {
        showShareBtn() {
            // if (this.playerMode.shareUrl && Unit.queryString('timestamp')=='') {
                return true;
            // } else {
            //     return false
            // }
        },
        alertPositionStyle() {
            if(this.isMobile) {
                return {
                    top: '10%',
                    // transform: 'translateY(-50%)',
                    left: '1.89rem'
                }
            } else {
                return {
                    top: '75px',
                    right: '20px',
                    // position: 'absolute'
                }
            }
        },
        playerModeClass() {
            // Log.info("playerModeClass", this.playerMode, this.isInteractiveMode, this.larksr);
            if (this.playerMode.showPlayerList && this.isInteractiveMode) {
                return "playerMode mobile";
            } else {
                return "playerMode hide";
            }
        },
        isInteractiveMode() {
            return this.larksr?.isInteractiveMode;
        },
        isPlayer() {
            return this.playerMode.userType == UserType.Player;
        },
        playerModeStr() {
            return this.isInteractiveMode ?
                this.ui.playerModeInteractive :
                this.ui.playerModeNormal;
        },
        userTypeStr() {
            return this.isPlayer ?
                this.ui.userTypePlayer :
                this.ui.userTypeObserver;
        },
        isTaskOwner() {
            return this.playerMode.isTaskOwner;
        },
        taskOwnerStr() {
            // return "管理员";
            return this.isTaskOwner ? this.ui.playerOwner : "";
        },
        copyShareAuthCodeText() {
            return this.playerMode.authCode ? this.ui.playerCopy : "";
        },
        shareUrl() {
            if (!this.larksr) {
                return "";
            }
            const { params } = this.larksr;
            let path = process.env.NODE_ENV === "development"? '/webclient': '/webclient/' ;
            // Log.info("larksr params", params);
            let shareUrl = "";
            // this.shareUrl = window.location.href.replace(/userType=[0-1]/, (match) => {
            //     Log.info("type match", match);
            //     return "userType=0";
            // });
            // this.shareUrl = this.shareUrl.replace(/(^|&)nickName=([^&]*)(&|$)/, (match) => {
            //     Log.info("nick name match", match);
            //     return "&";
            // });
            // 防止刷新url
            const urlBase = process.env.NODE_ENV === 'production' ? window.location.origin : process.env.VUE_APP_API_URL;
            let searchUrl = "";

            searchUrl += "appliId=" + params.appliId + "&";

            if (params.authCode && params.authCode != 'null') {
                searchUrl += "authCode=" + params.authCode + "&";
            } else if (Load.authCode && Load.authCode != 'null') {
                searchUrl += "authCode=" + Load.authCode + "&";
            } else {
                searchUrl += "taskId=" + params.taskid + "&";
            }

            searchUrl += "codeRate=" + params.codeRate + "&";
            searchUrl += "frameRate=" + params.frameRate + "&";

            if (params.groupId && params.groupId != 'null') {
                searchUrl += "groupId=" + params.groupId + "&";
            }
            if (Load.accessType && Load.accessType != '') {
                searchUrl += "accessType=" + Load.accessType + "&";
            }
            if (Load.shareId && Load.shareId != '') {
                searchUrl += "shareId=" + Load.shareId + "&";
            }


            searchUrl += "wsProxy=" + params.wsProxy + "&";
            // only ob
            searchUrl += "playerMode=" + params.playerMode + "&userType=0";

            shareUrl = urlBase + path + "?" + searchUrl;

            // Log.info("share url", shareUrl);
            return shareUrl;
        },
        ...mapState({
            larksr: state => state.larksr,
            isMobile: state => state.isMobile,
            ui: state => state.ui,
            playerMode: state => state.playerMode,
        })
    },
    methods: {
        onSelectItem(index) {
            const player = this.playerMode.playerList[index];
            Log.info('onSelectItem', index, player);
            if (this.playerMode.playerModeType == PlayerModeType.MutiPlayer) {
                Log.info("MutiPlayer mode no change.");
                return;
            }
            if (!this.isTaskOwner) {
                this.toast({text: this.ui.playerNotOwner, position: 2});
            } else {
                if (player.userType == UserType.Player) {
                    this.toast({text: this.ui.playerAlready, position: 2});
                } else {
                    this.toast({text: this.ui.playerChanging, position: 2});
                    if (this.larksr) {
                        this.larksr.changeOperater(player.userId);
                    }
                }
            }
        },
        toggleShareButton() {
            this.showShare = !this.showShare;
        },
        onClose() {
            Log.info('onClose');
            this.setShowPlayerList(false);
        },
        ...mapMutations({
            'setShowPlayerList': 'playerMode/setShowPlayerList',
        }),
        ...mapActions({
            'toast': 'toast/toast',
            'notify': 'notifyBar/notify',
            'showInfo': 'settingInfoPannel/showInfo',
            'closeInfo': 'settingInfoPannel/closeInfo',
            'alert': 'modalAlert/showModalAlert',
            'confirm': 'modalConfirm/showModalConfirm',
        }),
    },
    mounted() {
        Log.info('clipboard', clipboard);
        Log.info('show player mode', this.playerMode);
        if (this.isPlayer) {
            Log.info("is player. set share href to ob.");
        }

        // init share button
        if (!this.copyBtn) {
            if (this.$refs['copyBtn']) {
                this.copyBtn = new clipboard(this.$refs['copyBtn']);
            }
            Log.info("copy btn ", this.copyBtn, this.$refs['copyBtn'], this.$refs, this.shareUrl);
            if (this.copyBtn) {
                this.copyBtn.on('success', (e) => {
                    Log.info("copy ", e.text);
                    e.clearSelection();
                    this.toast({text: this.ui.playerCopyShareUrl, position: 2});
                });

                this.copyBtn.on('error', (e) => {
                    this.toast({text: this.ui.playerCopyShareUrlFailed, position: 2});
                });
            }
        }

        // copy room coe
        if (!this.copyAuthCodeBtn) {
            if (this.$refs['copy-authcode-button']) {
                this.copyAuthCodeBtn = new clipboard(this.$refs['copy-authcode-button']);
            }
            Log.info("copy room code btn ", this.copyAuthCodeBtn, this.$refs['copy-authcode-button'], this.$refs, this.playerMode.authCode);
            if (this.copyAuthCodeBtn) {
                this.copyAuthCodeBtn.on('success', (e) => {
                    Log.info("copy ", e.text, e);
                    e.clearSelection();
                    this.toast({text: this.ui.playerCopyAuthCodeSuccess, position: 2});
                });

                this.copyAuthCodeBtn.on('error', (e) => {
                    this.toast({text: this.ui.playerCopyAuthCodeFailed, position: 2});
                });
            }
        }
    },
    beforeDestroy() {
        this.copyAuthCodeBtn = null;
        this.copyBtn = null;
    }
}
</script>
<style lang="scss" scoped>
@import 'player_mode.scss';
</style>
