// ui-mobile-vue/src/components/toast/toast.vue
<template>
    <div v-if="toast.show" class="toast" :style="toastPosition">
        <span class="toastText" :style="toastText">{{toast.text}}</span>
    </div>
</template>
<script>
import { 
    mapState, 
}                 from 'vuex'
import { 
    ToastPosition 
}                 from '@/store/modules/toast'

export default {
    name: 'Toast',
    computed: {
        toastText() {
            if (this.toast.level == 3) {
                return {
                    // 'border': '1px solid #F76260',
                    'background-color': 'rgba(18, 37, 95, 1.0)',
                    color: 'white',
                }
            } else {
                return {};
            }
        },
        toastPosition() {
            const position = this.toast.position;
            let top = "";
            if (position) {
                if (position === ToastPosition.UP) {
                    top = '3%';
                } else if (position === ToastPosition.DOWN) {
                    top = '85%';
                }
            }
            if (this.toast.level == 3) {
                return {
                    // 'border': '1px solid #F76260',
                    // 'background-color': 'rgba(18, 37, 95, 1.0)',
                    // color: 'white',
                    top,
                }
            } else {
                return {
                    top,
                }
            }
        },
        ...mapState({
            'toast': state => { return state.toast.toast; }
        })
    }
}
</script>
<style lang="scss" scoped>
@import "toast.scss";
</style>

// ui-react/src/components/toast/toast.jsx
import './toast.scss';
import { ToastPosition, clearToast } from '../../store/modules/toast';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect, useState } from 'react';

export default function Toast() {
  const dispatch = useDispatch();
  const toast = useSelector(state => state.toast.toast);

  const [toastText, setToastText] = useState({});
  const [toastPosition, setToastPosition] = useState({});
  const [timer, setTimer] = useState(null);
  useEffect(() => {
    if (toast.level == 3) {
      setToastText({
        'backgroundColor': 'var(--webclient-toast-bg-1)',
        'color': 'var(--webclient-toast-font-color)'
      });
    } else {
      setToastText({});
    }

    const position = toast.position;
    let top = "";
    if (position) {
      if (position === ToastPosition.UP) {
        top = '7%';
      } else if (position === ToastPosition.DOWN) {
        top = '85%';
      }
    };
    setToastPosition({
      'top': top
    });

    if(toast.show===true) {
      const timeout/*: number*/ = toast.timeout ? toast.timeout : 5000;

      const t = window.setTimeout(() => {
				dispatch(clearToast());
			}, timeout);
      setTimer(t);
    }

    return() => {
      if(timer) clearTimeout(timer);
    }
  }, [toast]);
  return(
    <div>
      {toast.show &&
        <div className="toast" style={toastPosition}>
          <span className="toastText" style={toastText}>{toast.text}</span>
        </div>
      }
    </div>
  )
}
