// ui-vue3/src/components/toast/toast.vue
<template>
    <div v-if="toast.show" class="toast" :style="toastPosition">
        <span class="toastText" :style="toastText">{{toast.text}}</span>
    </div>
</template>
<script setup>
import { ToastPosition, useToastStore  } from '@/stores/toast.js'
import { useCommStore } from '@/stores/comm.js';

const commStore = useCommStore();
const toastStore = useToastStore();

const toast = computed(() => toastStore.toast);

const toastText = computed(() => {
    if (toast.value.level == 3) {
        return {
            'background-color': 'var(--webclient-toast-bg-1)',
            color: 'var(--webclient-toast-font-color)',
        }
    } else {
        return {};
    }
})

const toastPosition = computed(() => {
    const position = toast.value.position;
    let top = "";
    if (position) {
        if (position === ToastPosition.UP) {
            top = '7%';
        } else if (position === ToastPosition.DOWN) {
            top = '85%';
        }
    }
    if (toast.value.level == 3) {
        return {
            top,
        }
    } else {
        return {
            top,
        }
    }
})

</script>
<style lang="scss" scoped>
@import "toast.scss";
</style>

// ui-react/src/components/toast/toast.jsx
import './toast.scss';
import { ToastPosition, clearToast } from '../../store/modules/toast';
import { useDispatch, useSelector } from 'react-redux';
import { useEffect, useState } from 'react';

export default function Toast() {
  const dispatch = useDispatch();
  const toast = useSelector(state => state.toast.toast);

  const [toastText, setToastText] = useState({});
  const [toastPosition, setToastPosition] = useState({});
  const [timer, setTimer] = useState(null);
  useEffect(() => {
    if (toast.level == 3) {
      setToastText({
        'backgroundColor': 'var(--webclient-toast-bg-1)',
        'color': 'var(--webclient-toast-font-color)'
      });
    } else {
      setToastText({});
    }

    const position = toast.position;
    let top = "";
    if (position) {
      if (position === ToastPosition.UP) {
        top = '7%';
      } else if (position === ToastPosition.DOWN) {
        top = '85%';
      }
    };
    setToastPosition({
      'top': top
    });

    if(toast.show===true) {
      const timeout/*: number*/ = toast.timeout ? toast.timeout : 5000;

      const t = window.setTimeout(() => {
				dispatch(clearToast());
			}, timeout);
      setTimer(t);
    }

    return() => {
      if(timer) clearTimeout(timer);
    }
  }, [toast]);
  return(
    <div>
      {toast.show &&
        <div className="toast" style={toastPosition}>
          <span className="toastText" style={toastText}>{toast.text}</span>
        </div>
      }
    </div>
  )
}
