// ui-mobile-vue-new/src/components/modal_setting/modal_setting.vue
<template>
  <div class="customContentAlert" :style="viewPortStyle">
      <div class="customContentAlert-container">
          <div class="customContentAlert-title">
              <div class="customContentAlert-title-tab">
                  <p @click="tabClick('0')" :class="{'customContentAlert-title-tab-left':true, 'active':activeTab==='0'}">{{ui.setting}}</p>
                  <p @click="tabClick('1')" :class="{'customContentAlert-title-tab-right':true, 'active':activeTab==='1'}">{{ ui.viewTab }}</p>
              </div>
              <div class="close" @click="onCancel">
                  <i class="el-icon-close"></i>
              </div>
          </div>
          <template v-if="activeTab==='0'">
            <div class="customContentAlert-content">
              <div class="quality content-row setting-row">
                  <span>{{ ui.mouse }}</span>
                  <div class="quality-btn">
                    <p @click="toggleInitCursorMode" :class="{'quality-btn-active': !initCursorMode}">{{ui.mouseModeAuto}}</p>
                    <p @click="toggleInitCursorMode" :class="{'quality-btn-active': initCursorMode}">{{ui.mosueModeLock}}</p>
                  </div>
                </div>
                <div class="customContentAlert-divider"></div>
                <div class="quality content-row setting-row">
                  <span>{{ui.cipboardParseOn}}</span>
                  <div class="ratio-btn">
                    <div>
                      <PvtSwitch v-model="cipboardParseChecked" @change="toggleSyncClipboardParseEvent"/>
                    </div>
                  </div>
                </div>
                <div class="customContentAlert-divider"></div>
                <template v-if="isInteractiveMode">
                  <div class="quality content-row setting-row">
                    <span>{{ ui.showPlayerList }}</span>
                    <div class="ratio-btn">
                      <div>
                        <PvtSwitch v-model="playerListChecked" @change="togglePlayerList"/>
                      </div>
                    </div>
                  </div>
                  <div class="customContentAlert-divider"></div>
                </template>
                <div class="quality content-row setting-row">
                  <span>{{ ui.volume }}</span>
                  <div class="quality-btn">
                    <i class="iconfont icon-mute" style="margin-right: 10px;font-size: 20px;"></i>
                    <Slider v-on:change="onVolmueChange" />
                  </div>
                </div>
                <div class="customContentAlert-divider" style="margin-bottom: 0;"></div>
            </div>
          </template>
          <template v-if="activeTab==='1'">
            <div class="customContentAlert-content">
                <div class="quality content-row">
                  <span>{{ ui.quality }}</span>
                  <div class="quality-btn">
                    <p @click="qualityClick('0')" :class="{'quality-btn-active': selectFps===60&&selectCoderate===8000}"> {{ ui.quality1 }}</p>
                    <p @click="qualityClick('1')" :class="{'quality-btn-active': selectFps===60&&selectCoderate===10000}">{{ ui.quality2 }}</p>
                    <p @click="qualityClick('2')" :class="{'quality-btn-active': selectFps===60&&selectCoderate===20000}">{{ ui.quality3 }}</p>
                    <p @click="qualityClick('3')" :class="{'quality-btn-active': selectFps===60&&selectCoderate===50000}">{{ ui.quality4 }}</p>
                  </div>
                </div>
                <div class="customContentAlert-divider"></div>
                <div class="custom custom-code content-row">
                  <span>{{ ui.custom }}</span>
                  <div class="custom-content">
                    <span>{{ ui.codeRate }}</span>
                    <el-select @change="onChangeBitrate" v-model="selectCoderate" size="mini" :placeholder="ui.liveBitrate">
                      <el-option v-for="(coderate, key) in coderates" v-bind:value="coderate" v-bind:key="key">
                          {{ coderate }} kbps
                      </el-option>
                    </el-select>
                  </div>
                </div>
                <div class="custom content-row">
                  <span></span>
                  <div class="custom-content">
                    <span>{{ ui.frameRate }}</span>
                    <el-select @change="onChangeCodeFps" v-model="selectFps" size="mini" :placeholder="ui.liveFPS">
                      <el-option v-for="(fps, key) in fpss" v-bind:value="fps" v-bind:key="key">
                          {{ fps }} FPS
                      </el-option>
                    </el-select>
                  </div>
                </div>
                <div class="customContentAlert-divider"></div>
                <div class="quality content-row">
                  <span>{{ ui.ratio }}</span>
                  <div class="ratio-btn">
                    <p @click="toggleScaleToFillStretch" :class="{'quality-btn-active':isChangedScaledMode}">{{ ui.scale }}</p>
                    <p @click="toggleScaleToFillStretch" :class="{'quality-btn-active':!isChangedScaledMode}">{{ui.scaleAuto}}</p>
                  </div>
                </div>
                <div class="customContentAlert-divider"></div>
                <div class="custom content-row">
                  <span>{{ui.resolutions}}</span>
                  <div class="custom-content">
                    <el-select v-model="selecteResolution" value-key="id" size="mini" :placeholder="ui.resolutions" @change="onChangeResolution">
                      <el-option v-for="(resolution, key) in resolutions" v-bind:value="resolution" v-bind:key="key" :label="resolution.width+ ' x ' +resolution.height">
                      </el-option>
                    </el-select>
                  </div>
                </div>
                <template v-if="larksr.params.appliType===1 ||larksr.params.appliType===2">
                  <div class="customContentAlert-divider"></div>
                  <div class="quality content-row">
                    <span>{{ ui.aerial }}</span>
                    <div class="ratio-btn">
                      <div>
                        <PvtSwitch v-model="checked" @change="aerialCheckedChange"/>
                      </div>
                    </div>
                  </div>
                </template>
                <div class="customContentAlert-divider" style="margin-bottom: 0;"></div>
            </div>
          </template>
      </div>
  </div>
</template>
<script>
import Log from '@/utils/log';
import { mapState, mapGetters, mapMutations, mapActions } from 'vuex'
import PvtSwitch from '../switch_pvt/switch_pvt'
import Slider from '../slider/slider';

export default {
  name: 'ModalSetting',
  components: {
    PvtSwitch,
    Slider
  },
  computed: {
    // 是否显示玩家列表勾选框
    playerListChecked: {
      get() {
        return this.playerMode.showPlayerList;
      },
      set() {}
    },
    // 同步本地剪贴板勾选框
    cipboardParseChecked: {
      get() {
         return this.syncClipboardParseEvent;
      },
      set() {}
    },
    // 鸟瞰模式勾选框
    checked: {
      get() {
        return this.aerialViewCheck;
      },
      set() {}
    },
    // 画质
    qualityTab() {
      return this.qualityMode;
    },
    // 码率
    selectCoderate() {
      return this.coderate;
    },
    // 帧率
    selectFps() {
      return this.fps;
    },
    // 分辨率
    selecteResolution() {
      return this.resolution;
    },
    ...mapGetters({
      viewPortStyle: 'viewPortStyle',
      isChangedScaledMode: 'isChangedScaledMode',
      initCursorMode: "initCursorMode",
      isInteractiveMode: 'playerMode/isInteractiveMode',
    }),
    ...mapState({
      larksr: state => state.larksr,
      ui: state => state.ui,
      playerMode: state => state.playerMode,
      syncClipboardParseEvent: state => state.syncClipboardParseEvent,
      showAerialView: state => state.showAerialView,
      qualityMode: state => state.modalSetting.qualityMode,
      coderate: state => state.modalSetting.coderate,
      fps: state => state.modalSetting.fps,
      resolution: state => state.modalSetting.resolution,
      aerialViewCheck: state => state.modalSetting.aerialViewCheck,
    })
  },
  data() {
    return {
      activeTab: '0', // 画面
      coderates: [
        8000,
        10000,
        15000,
        20000,
        30000,
        50000,
        100000
      ],
      fpss: [
        30,
        60,
      ],
      resolutions: [
        { id: '40961080', width: 4096, height: 1080 },
        { id: '40962160', width: 4096, height: 2160 },
        { id: '38402160', width: 3840, height: 2160 },
        { id: '38401080', width: 3840, height: 1080 },
        { id: '25601440', width: 2560, height: 1440 },
        { id: '20481536', width: 2048, height: 1536 },
        { id: '19201080', width: 1920, height: 1080 },
        { id: '19201440', width: 1920, height: 1440 },
        { id: '1600900', width: 1600, height: 900 },
        { id: '1366768', width: 1366, height: 768 },
        { id: '1280720', width: 1280, height: 720 },
        { id: '1280600', width: 1280, height: 600 },
        { id: '21803840', width: 2180, height: 3840 },
        { id: '10801920', width: 1080, height: 1920 },
        { id: '7201280', width: 720, height: 1280 },
        { id: '15362048', width: 1536, height: 2048 },
      ],
    }
  },
  methods: {
    onCancel() {
      this.setIsShowSettingAlert(false);
    },
    onSubmit() {

    },
    togglePlayerList() {
      this.setShowPlayerList(!this.playerMode.showPlayerList);
    },
    onVolmueChange(value) {
      if (this.larksr) {
        this.larksr.videoElement.volume = value / 100;
        // TODO config audio
        this.larksr.audioElement.volume = value / 100;
      }
    },
    tabClick(type) {
      this.activeTab = type;
    },
    qualityClick(type) {
      this.setQualityMode(type);
      switch(type) {
        case '0':
          this.onChangeBitrate(8000);
          this.onChangeCodeFps(60);
          break;
        case'1':
          this.onChangeBitrate(10000);
          this.onChangeCodeFps(60);
          break;
        case '2':
          this.onChangeBitrate(20000);
          this.onChangeCodeFps(60);
          break;
        case '3':
          this.onChangeBitrate(50000);
          this.onChangeCodeFps(60);
          break;
      }

    },
    onChangeBitrate(coderate) {
      Log.info('onChangeBitrate', coderate);
      this.coderateChange(coderate);
      this.larksr.setVideoBitrateKbps(coderate);
    },
    onChangeCodeFps(fps) {
      Log.info('onChangeCode', fps);
      this.codeFpsChange(fps);
      this.larksr.setVideoFps(fps);
    },
    onChangeResolution(val) {
      Log.info("onChangeResolution", val);
      this.setResolution(JSON.parse(JSON.stringify(val)));
      this.larksr?.setCloudAppSize(val.width, val.height);
    },
    aerialCheckedChange(val) {
      this.setAerialViewCheck(val);
      if(val === false) {
        if(this.aerailView)this.toggleAerailView();
        this.setCustomContentAlertTitle('');
        this.larksr.stopAerialview();
      } else {
        this.onCancel();
        if(!this.aerailView)this.toggleAerailView();
        this.setShowAerialView(true);
        this.setCustomContentAlertTitle(this.ui.aerial);
      }
    },
    resetResolution() {
      let found = false;
      for (let res of this.resolutions) {
        if (res.width === this.larksr.currentAppSize.width && res.height === this.larksr.currentAppSize.height) {
          found = true;
        }
      }

      if (!found) {
        this.resolutions.push({
          id: this.larksr.currentAppSize.width+''+this.larksr.currentAppSize.height,
          width: this.larksr.currentAppSize.width,
          height: this.larksr.currentAppSize.height,
        });
      }

      this.setResolution({
        id: this.larksr.currentAppSize.width+''+this.larksr.currentAppSize.height,
        width: this.larksr.currentAppSize.width,
        height: this.larksr.currentAppSize.height,
      })
    },
    ...mapMutations({
      setIsShowSettingAlert: 'modalSetting/setIsShowSettingAlert',
      setCustomContentAlertTitle: 'customContentAlert/setCustomContentAlertTitle',
      setShowPlayerList: 'playerMode/setShowPlayerList',
      setQualityMode: 'modalSetting/setQualityMode',
      setResolution: 'modalSetting/setResolution',
      setAerialViewCheck: 'modalSetting/setAerialViewCheck',
      setShowAerialView: 'setShowAerialView',
    }),
    ...mapActions({
        toggleScaleToFillStretch: 'toggleScaleToFillStretch',
        toggleAerailView: 'toggleAerailView',
        toggleInitCursorMode: 'toggleInitCursorMode',
        toggleSyncClipboardParseEvent: "toggleSyncClipboardParseEvent",
        coderateChange: 'modalSetting/coderateChange',
        codeFpsChange: 'modalSetting/codeFpsChange',
      })
  },
    created() {
    if(this.larksr.params.useWebCodec) {
      this.resolutions.unshift({ id: '76804320', width: 7680, height: 4320 })
    }
  },
  mounted() {
    if (this.larksr && this.larksr.currentAppSize) {
      this.larksr.on("appresize", () => {
        this.resetResolution();
      });
      this.resetResolution();
    }
  },
  beforeDestroy() {},
}
</script>
<style lang="scss" scoped>
@import "modal_setting.scss";
</style>

// ui-react/src/components/modalSetting/modalSetting.jsx
import { useDispatch, useSelector } from 'react-redux';
import Log from '@/utils/log';
import './modalSetting.scss';
import { CloseOutlined } from '@ant-design/icons';
import { useEffect, useState } from 'react';
import { setIsShowSettingAlert, setQualityMode, coderateChange, codeFpsChange, setResolution, setAerialViewCheck } from '../../store/modules/modalSetting';
import { toggleInitCursorMode, toggleSyncClipboardParseEvent, setShowAerialView, toggleScaleToFillStretch } from '../../store/modules/comm';
import { setShowPlayerList } from '../../store/modules/playerMode';
import { setCustomContentAlertTitle } from '../../store/modules/customContentAlert';
import PvtSwitch from '../switchPvt/switchPvt';
import Slider from '../slider/slider';
import { Select } from 'antd';

export default function ModalSetting() {
  const dispatch = useDispatch();
  
  const larksr = useSelector(state => state.comm.larksr);
  const ui = useSelector(state => state.comm.ui);
  // const [initCursorMode, setInitCursorMode] = useState(false);
  const [isInteractiveMode, setIsInteractiveMode] = useState(false);

  const screenStateScalMode = useSelector(state => state.comm.larksr.screenState.scaleMode);
  const paramsScalMode = useSelector(state => state.comm.larksr.params.scaleMode);

  const syncClipboardParseEvent = useSelector(state => state.comm.syncClipboardParseEvent);
  const showPlayerList = useSelector(state => state.playerMode.showPlayerList);
  const resolution = useSelector(state => state.modalSetting.resolution);
  const aerialViewCheck = useSelector(state => state.modalSetting.aerialViewCheck);
  const selectFps = useSelector(state => state.modalSetting.fps);
  const selectCoderate = useSelector(state => state.modalSetting.coderate);
  const initCursorMode = useSelector(state => state.comm.larksr.initCursorMode)
  

  useEffect(() => {
    // setInitCursorMode(larksr ? larksr.initCursorMode : false);
    setIsInteractiveMode(larksr ? larksr.isInteractiveMode : false);
  }, [larksr]);

  const [activeTab, setActiveTab] = useState('0'); // 画面
  const tabClick = (type) => {
    setActiveTab(type);
  };
  const onCancel = () => {
    dispatch(setIsShowSettingAlert(false));
  };

  const onVolmueChange = (value) => {
    if (larksr) {
      larksr.videoElement.volume = value / 100;
      larksr.audioElement.volume = value / 100;
    }
  };
  
  const onChangeBitrate = (coderate) => {
    dispatch(coderateChange(coderate));
    larksr.setVideoBitrateKbps(coderate);
    Log.info('onChangeBitrate', coderate, selectCoderate);
  };
  const onChangeCodeFps = (fps) => {
    Log.info('onChangeCode1', fps);
    dispatch(codeFpsChange(fps));
    larksr.setVideoFps(fps);
  };
  const qualityClick = (type) => {
    dispatch(setQualityMode(type));
    switch(type) {
      case '0':
        onChangeBitrate(8000);
        onChangeCodeFps(60);
        break;
      case'1':
        onChangeBitrate(10000);
        onChangeCodeFps(60);
        break;
      case '2':
        onChangeBitrate(20000);
        onChangeCodeFps(60);
        break;
      case '3':
        onChangeBitrate(50000);
        onChangeCodeFps(60);
        break;
    }

  };

  
  const onChangeResolution = (val) => {
    Log.info("onChangeResolution", val);
    const valArr = val.split('-');
    dispatch(setResolution(val));
    larksr?.setCloudAppSize(valArr[0], valArr[1]);
  };
  const resetResolution = () => {
    let found = false;
    for (let res of resolutions) {
      const obj = res.value.split('-');
      if (obj[0] == larksr.currentAppSize.width && obj[1] == larksr.currentAppSize.height) {
        found = true;
      }
    }
    if (!found) {
      let val = JSON.parse(JSON.stringify(resolutions));
      val.push({
        value: larksr.currentAppSize.width+'-'+larksr.currentAppSize.height,
        label: larksr.currentAppSize.width+' x '+larksr.currentAppSize.height
      });
      setResolutions(val);
    }
    dispatch(setResolution(larksr.currentAppSize.width+'-'+larksr.currentAppSize.height));
  };
  
  const aerialCheckedChange = (val) => {
    dispatch(setAerialViewCheck(val));
    if(val === false) {
      dispatch(setCustomContentAlertTitle(''));
      larksr.stopAerialview();
    } else {
      onCancel();
      dispatch(setShowAerialView(true));
      dispatch(setCustomContentAlertTitle(ui.aerial));
    }
  };

  const coderates = [
    8000,
    10000,
    15000,
    20000,
    30000,
    50000,
    100000
  ];

  const scaleFn = () => {
    dispatch(toggleScaleToFillStretch());
  }
  const [resolutions, setResolutions] = useState([
    {value: '4096-1080', label: '4096 x 1080'},
    {value: '4096-160', label: '4096 x 2160'},
    {value: '3840-2160', label: '3840 x 2160'},
    {value: '3840-1080', label: '3840 x 1080'},
    {value: '2560-1440', label: '2560 x 1440'},
    {value: '2048-1536', label: '2048 x 1536'},
    {value: '1920-1080', label: '1920 x 1080'},
    {value: '1920-1440', label: '1920 x 1440'},
    {value: '1600-900', label: '1600 x 900'},
    {value: '1366-768', label: '1366 x 768'},
    {value: '1280-720', label: '1280 x 720'},
    {value: '1280-600', label: '1280 x 600'},
    {value: '2180-3840', label: '2180 x 3840'},
    {value: '1080-1920', label: '1080 x 1920'},
    {value: '720-1280', label: '720 x 1280'},
    {value: '1536-2048', label: '1536 x 2048'},
    // {value: { id: '40961080', width: 4096, height: 1080 }, label: '4096 x 1080'},
  ]);

  useEffect(() => {
    if (larksr && larksr.currentAppSize) {
      larksr.on("appresize", () => {
        resetResolution();
      });
      resetResolution();
    }
  }, [])
  return(
    <div className="customContentAlert" style={{width: larksr?.screenState.viewPort.width, height: larksr?.screenState.viewPort.height}}>
      <div className="customContentAlert-container">
          <div className="customContentAlert-title">
              <div className="customContentAlert-title-tab">
                  <p onClick={() => tabClick('0')} className={`customContentAlert-title-tab-left${activeTab==='0'? ' active':''}`}>{ui.setting}</p>
                  <p onClick={() => tabClick('1')} className={`customContentAlert-title-tab-right${activeTab==='1'?' active':''}`}>{ ui.viewTab }</p>
              </div>
              <div className="close" onClick={onCancel}>
                <CloseOutlined  style={{fontSize: '1.8rem'}}/>
              </div>
          </div>
          { activeTab==='0' &&
            <div className="customContentAlert-content">
              <div className="quality content-row setting-row">
                  <span>{ ui.mouse }</span>
                  <div className="quality-btn">
                    <p onClick={() => dispatch(toggleInitCursorMode())} className={`${!initCursorMode?'quality-btn-active':''}`}>{ui.mouseModeAuto}</p>
                    <p onClick={() => dispatch(toggleInitCursorMode())} className={`${initCursorMode?'quality-btn-active':''}`}>{ui.mosueModeLock}</p>
                  </div>
              </div>
                <div className="customContentAlert-divider"></div>
                <div className="quality content-row setting-row">
                  <span>{ui.cipboardParseOn}</span>
                  <div className="ratio-btn">
                    <div>
                      <PvtSwitch checked={syncClipboardParseEvent} change={() => dispatch(toggleSyncClipboardParseEvent())} />
                    </div>
                  </div>
                </div>
                <div className="customContentAlert-divider"></div>
                { isInteractiveMode && 
                  <div>
                    <div className="quality content-row setting-row">
                      <span>{ ui.showPlayerList }</span>
                      <div className="ratio-btn">
                        <div>
                          <PvtSwitch checked={showPlayerList} change={setShowPlayerList(!showPlayerList)}/>
                        </div>
                      </div>
                    </div>
                    <div className="customContentAlert-divider"></div>
                  </div>
                }
                <div className="quality content-row setting-row">
                  <span>{ ui.volume }</span>
                  <div className="quality-btn">
                    <i className="iconfont icon-mute" style={{marginRight: '10px',fontSize: '20px'}}></i>
                    <Slider change={onVolmueChange} />
                  </div>
                </div>
                <div className="customContentAlert-divider" style={{marginBottom: '0'}}></div>
            </div>
          }
          {activeTab==='1' &&
            <div className="customContentAlert-content">
                <div className="quality content-row">
                  <span>{ ui.quality }</span>
                  <div className="quality-btn">
                    <p onClick={() => qualityClick('0')} className={`${(selectFps===60&&selectCoderate===8000)?'quality-btn-active':''}`}> { ui.quality1 }</p>
                    <p onClick={() => qualityClick('1')} className={`${(selectFps===60&&selectCoderate===10000)?'quality-btn-active': ''}`}>{ ui.quality2 }</p>
                    <p onClick={() => qualityClick('2')} className={`${(selectFps===60&&selectCoderate===20000)?'quality-btn-active': ''}`}>{ ui.quality3 }</p>
                    <p onClick={() => qualityClick('3')} className={`${(selectFps===60&&selectCoderate===50000)?'quality-btn-active': ''}`}>{ ui.quality4 }</p>
                  </div>
                </div>
                <div className="customContentAlert-divider"></div>
                <div className="custom custom-code content-row">
                  <span>{ ui.custom }</span>
                  <div className="custom-content">
                    <span>{ ui.codeRate }</span>
                    <Select 
                      value={selectCoderate}
                      onChange={onChangeBitrate}
                      options={[
                        {value: 8000, label: 8000+' kbps'},
                        {value: 10000, label: 10000+' kbps'},
                        {value: 15000, label: 15000+' kbps'},
                        {value: 20000, label: 20000+' kbps'},
                        {value: 30000, label: 30000+' kbps'},
                        {value: 50000, label: 50000+' kbps'},
                        {value: 100000, label: 100000+' kbps'},
                      ]}
                    />
                  </div>
                </div>
                <div className="custom content-row">
                  <span></span>
                  <div className="custom-content">
                    <span>{ ui.frameRate }</span>
                    <Select 
                      value={selectFps}
                      onChange={onChangeCodeFps}
                      options={[
                        {value: 30, label: 30+' FPS'},
                        {value: 60, label: 60+' FPS'},
                      ]}
                    />
                  </div>
                </div>
                <div className="customContentAlert-divider"></div>
                <div className="quality content-row">
                  <span>{ ui.ratio }</span>
                  <div className="ratio-btn">
                    <p onClick={scaleFn} className={`${screenStateScalMode != paramsScalMode?'quality-btn-active':''}`}>{ ui.scale }</p>
                    <p onClick={scaleFn} className={`${!(screenStateScalMode != paramsScalMode)?'quality-btn-active':''}`}>{ui.scaleAuto}</p>
                  </div>
                </div>
                <div className="customContentAlert-divider"></div>
                <div className="custom content-row">
                  <span>{ui.resolutions}</span>
                  <div className="custom-content">
                  <Select 
                      value={resolution}
                      onChange={onChangeResolution}
                      options={resolutions}
                    />
                  </div>
                </div>
                {
                  (larksr.params.appliType===1 ||larksr.params.appliType===2) && 
                  <div>
                    <div className="customContentAlert-divider"></div>
                    <div className="quality content-row">
                      <span>{ ui.aerial }</span>
                      <div className="ratio-btn">
                        <div>
                          <PvtSwitch checked={aerialViewCheck} change={aerialCheckedChange}/>
                        </div>
                      </div>
                    </div>
                  </div>
                }
                <div className="customContentAlert-divider" style={{marginBottom: 0}}></div>
            </div>
          }
      </div>
  </div>
  
  )
}
