// ui-react/src/components/modalHelp/modalHelp.jsx
import './modalHelp.scss'
import { CloseOutlined, CaretDownOutlined } from '@ant-design/icons'
import ContentAlert from '../customContentAlert/customContentAlert'
import { setIsShowHelpAlert } from '../../store/modules/modalHelp'
import { setCustomContentAlertTitle } from '../../store/modules/customContentAlert'
import { useEffect, useRef, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'

export default function modalHelp() {
  const dispatch = useDispatch();

  const ui = useSelector(state => state.comm.ui);

  const alertPositionStyle = {
    top: '75px',
    right: '20px',
    position: 'absolute'
  };

  const [helpList, setHelpList] = useState([
    {title: ui.helpTitle1,content: ui.helpContent1},
    {title: ui.helpTitle2,content: ui.helpContent2}
  ])
  const isMobile = useSelector(state => state.comm.isMobile);
  useEffect(() => {
    let list = [
      {title: ui.helpTitle1,content: ui.helpContent1},
      {title: ui.helpTitle2,content: ui.helpContent2}
    ]
    if(isMobile) {
      list.push( {title: ui.helpTitle4,content: ui.helpContent4})
    }
    setHelpList(list);
  }, [])


  const onCancel = () => {
    dispatch(setIsShowHelpAlert(false));
    dispatch(setCustomContentAlertTitle(''));
  };

  const [helpRefList, setHelpRefList] = useState([]);
  const [contentRefList, setContentRefList] = useState([]);
  const handleHelpRef = (el, index) => {
    if (el) {
      let list = helpRefList;
      list[index] = el;
      setHelpRefList(list);
    }
  }
  const handleContentRef = (el, index) => {
    if (el) {
      let list = contentRefList;
      list[index] = el;
      setContentRefList(list);
    }
  }

  // click
  const [active, setActive] = useState('');
  const caretFn = (index) => {
    if(active === index) {
      setActive('');
      helpRefList[index].style.transform = 'rotate(0deg)';
      contentRefList[index].style['maxHeight'] = '0px';
      contentRefList[index].style['margin-bottom'] = '0px';
      
    } else {
      setActive(index);
      
      helpRefList[index].style.transform = 'rotate(-180deg)';
      contentRefList[index].style['maxHeight'] = '28.3rem';
      contentRefList[index].style['margin'] = '0.5rem 0';
    }
  
    helpRefList[index].style.transition = 'all 0.1s';
    contentRefList[index].style.transition = 'all 0.3s';
  };

  const falist = useRef(null);
  return (
    <ContentAlert
      alertPositionStyle={alertPositionStyle}
      close={
        <div onClick={onCancel}>
          <CloseOutlined style={{fontSize: '1.8rem'}} />
          </div>
      }
      content={
        helpList.map((item, index) => {
          return (
            <div ref={falist} className="help-row" key={item.title}>
              <div className="help-row-title" onClick={() => caretFn(index)}>
                <p>{item.title}</p>
                <div ref={el => handleHelpRef(el,index)}>
                  <CaretDownOutlined />
                </div>
              </div>
              <div className="help-row-content" ref={el => handleContentRef(el, index)}>
                {item.content}
              </div>
            </div>
          )
        })
      }
    >
    </ContentAlert>
  )
}

// ui-mobile-vue-new/src/components/modal_help/modal_help.vue
<template>
  <ContentAlert :alertPositionStyle="alertPositionStyle">
    <template v-slot:close>
      <div @click="onCancel">
          <i class="el-icon-close"></i>
      </div>
    </template>
    <template v-slot:content>
      <div v-for="(item, index) in helpList" class="help-row" :key="item.title">
        <div class="help-row-title" @click="caretFn(index)">
          <p>{{item.title}}</p>
          <i :ref="'caret'+index" class="el-icon-caret-bottom"></i>
        </div>
        <div class="help-row-content" :ref="'content'+index">
          {{item.content}}
        </div>
      </div>
    </template>
  </ContentAlert>
</template>
<script>
import { mapState } from 'vuex';
import ContentAlert from '../custom_content_alert/custom_content_alert'
import { mapMutations } from 'vuex'
export default {
  components: {
    ContentAlert
  },
  computed: {
    helpList() {
      let list = [
        {title: this.ui.helpTitle1,content: this.ui.helpContent1},
        {title: this.ui.helpTitle2,content: this.ui.helpContent2}
      ]
      if(this.isMobile) {
        list.push( {title: this.ui.helpTitle4,content: this.ui.helpContent4})
      }
      return list
    },

    ...mapState({
      isMobile: state => state.isMobile,
      ui: state => state.ui,
    }),
  },
  data () {
    return {
      active: '',
      alertPositionStyle: {
          top: '75px',
          right: '20px',
          position: 'absolute'
      }
    }
  },
  methods: {
    caretFn(index) {
      if(this.active === index) {
        this.active = '';
        this.$refs['caret'+index][0].style.transform = 'rotate(0deg)';
        this.$refs['content'+index][0].style['max-height'] = '0px';
        this.$refs['content'+index][0].style['margin-bottom'] = '0px';
      } else {
        this.active = index;
        this.$refs['caret'+index][0].style.transform = 'rotate(-180deg)';
        this.$refs['content'+index][0].style['max-height'] = '28.3rem';
        this.$refs['content'+index][0].style['margin-bottom'] = '20px';
      }

      this.$refs['caret'+index][0].style.transition = 'all 0.1s';
      this.$refs['content'+index][0].style.transition = 'all 0.3s';
    },
    onCancel() {
      this.setIsShowHelpAlert(false);
      this.setCustomContentAlertTitle('');
    },
    ...mapMutations({
      setIsShowHelpAlert: 'modalHelp/setIsShowHelpAlert',
      setCustomContentAlertTitle: 'customContentAlert/setCustomContentAlertTitle'
    }),
  }
}
</script>
<style lang='scss' scoped>
.help-row {
  border-bottom: 1px solid var(--webclient-dialog-divider);
  cursor: pointer;
  &-title {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.8rem 5px 1.8rem 0;
    box-sizing: border-box;
    >i {
      cursor: pointer;
      font-size: 2rem;
      transform: rotate(0deg);
    }
    >i.active {
      transform: rotate(180deg);
      transition: all 0.3s;
    }
    >p {
      margin: 0;
    }
  }
  &-content {
    text-align: left;
    margin-bottom: 0px;
    max-height: 0px;
    overflow: auto;
  }
}
</style>
